#######
# Compiled from kitcraft/functions/blocks/kitchen_counter.mcscript
# to .//data/kitcraft/functions/blocks/kitchen_counter/crafted.mcfunction
#
# Generated by Minecraft Script for 1.13
######

execute unless block ~ ~ ~ barrel{Items:[{Slot:2b,tag:{kitcraft:{CraftingTool:1}}}]} store result score @s kc_temp run data get block ~ ~ ~ Items[{Slot:2b}].Count
execute unless block ~ ~ ~ barrel{Items:[{Slot:2b,tag:{kitcraft:{CraftingTool:1}}}]} run scoreboard players remove @s kc_temp 1
execute unless block ~ ~ ~ barrel{Items:[{Slot:2b,tag:{kitcraft:{CraftingTool:1}}}]} store result block ~ ~ ~ Items[{Slot:2b}].Count byte 1 run scoreboard players get @s kc_temp

scoreboard players reset @s kc_temp
execute unless block ~ ~ ~ barrel{Items:[{Slot:3b,tag:{kitcraft:{CraftingTool:1}}}]} store result score @s kc_temp run data get block ~ ~ ~ Items[{Slot:3b}].Count
execute unless block ~ ~ ~ barrel{Items:[{Slot:3b,tag:{kitcraft:{CraftingTool:1}}}]} run scoreboard players remove @s kc_temp 1
execute unless block ~ ~ ~ barrel{Items:[{Slot:3b,tag:{kitcraft:{CraftingTool:1}}}]} store result block ~ ~ ~ Items[{Slot:3b}].Count byte 1 run scoreboard players get @s kc_temp

scoreboard players reset @s kc_temp
execute unless block ~ ~ ~ barrel{Items:[{Slot:4b,tag:{kitcraft:{CraftingTool:1}}}]} store result score @s kc_temp run data get block ~ ~ ~ Items[{Slot:4b}].Count
execute unless block ~ ~ ~ barrel{Items:[{Slot:4b,tag:{kitcraft:{CraftingTool:1}}}]} run scoreboard players remove @s kc_temp 1
execute unless block ~ ~ ~ barrel{Items:[{Slot:4b,tag:{kitcraft:{CraftingTool:1}}}]} store result block ~ ~ ~ Items[{Slot:4b}].Count byte 1 run scoreboard players get @s kc_temp

scoreboard players reset @s kc_temp
execute unless block ~ ~ ~ barrel{Items:[{Slot:11b,tag:{kitcraft:{CraftingTool:1}}}]} store result score @s kc_temp run data get block ~ ~ ~ Items[{Slot:11b}].Count
execute unless block ~ ~ ~ barrel{Items:[{Slot:11b,tag:{kitcraft:{CraftingTool:1}}}]} run scoreboard players remove @s kc_temp 1
execute unless block ~ ~ ~ barrel{Items:[{Slot:11b,tag:{kitcraft:{CraftingTool:1}}}]} store result block ~ ~ ~ Items[{Slot:11b}].Count byte 1 run scoreboard players get @s kc_temp

scoreboard players reset @s kc_temp
execute unless block ~ ~ ~ barrel{Items:[{Slot:12b,tag:{kitcraft:{CraftingTool:1}}}]} store result score @s kc_temp run data get block ~ ~ ~ Items[{Slot:12b}].Count
execute unless block ~ ~ ~ barrel{Items:[{Slot:12b,tag:{kitcraft:{CraftingTool:1}}}]} run scoreboard players remove @s kc_temp 1
execute unless block ~ ~ ~ barrel{Items:[{Slot:12b,tag:{kitcraft:{CraftingTool:1}}}]} store result block ~ ~ ~ Items[{Slot:12b}].Count byte 1 run scoreboard players get @s kc_temp

scoreboard players reset @s kc_temp
execute unless block ~ ~ ~ barrel{Items:[{Slot:13b,tag:{kitcraft:{CraftingTool:1}}}]} store result score @s kc_temp run data get block ~ ~ ~ Items[{Slot:13b}].Count
execute unless block ~ ~ ~ barrel{Items:[{Slot:13b,tag:{kitcraft:{CraftingTool:1}}}]} run scoreboard players remove @s kc_temp 1
execute unless block ~ ~ ~ barrel{Items:[{Slot:13b,tag:{kitcraft:{CraftingTool:1}}}]} store result block ~ ~ ~ Items[{Slot:13b}].Count byte 1 run scoreboard players get @s kc_temp

scoreboard players reset @s kc_temp
execute unless block ~ ~ ~ barrel{Items:[{Slot:20b,tag:{kitcraft:{CraftingTool:1}}}]} store result score @s kc_temp run data get block ~ ~ ~ Items[{Slot:20b}].Count
execute unless block ~ ~ ~ barrel{Items:[{Slot:20b,tag:{kitcraft:{CraftingTool:1}}}]} run scoreboard players remove @s kc_temp 1
execute unless block ~ ~ ~ barrel{Items:[{Slot:20b,tag:{kitcraft:{CraftingTool:1}}}]} store result block ~ ~ ~ Items[{Slot:20b}].Count byte 1 run scoreboard players get @s kc_temp

scoreboard players reset @s kc_temp
execute unless block ~ ~ ~ barrel{Items:[{Slot:21b,tag:{kitcraft:{CraftingTool:1}}}]} store result score @s kc_temp run data get block ~ ~ ~ Items[{Slot:21b}].Count
execute unless block ~ ~ ~ barrel{Items:[{Slot:21b,tag:{kitcraft:{CraftingTool:1}}}]} run scoreboard players remove @s kc_temp 1
execute unless block ~ ~ ~ barrel{Items:[{Slot:21b,tag:{kitcraft:{CraftingTool:1}}}]} store result block ~ ~ ~ Items[{Slot:21b}].Count byte 1 run scoreboard players get @s kc_temp

scoreboard players reset @s kc_temp
execute unless block ~ ~ ~ barrel{Items:[{Slot:22b,tag:{kitcraft:{CraftingTool:1}}}]} store result score @s kc_temp run data get block ~ ~ ~ Items[{Slot:22b}].Count
execute unless block ~ ~ ~ barrel{Items:[{Slot:22b,tag:{kitcraft:{CraftingTool:1}}}]} run scoreboard players remove @s kc_temp 1
execute unless block ~ ~ ~ barrel{Items:[{Slot:22b,tag:{kitcraft:{CraftingTool:1}}}]} store result block ~ ~ ~ Items[{Slot:22b}].Count byte 1 run scoreboard players get @s kc_temp

scoreboard players reset @s kc_temp
