#######
# Compiled from kitcraft/functions/blocks/kitchen_counter.mcscript
# to .//data/kitcraft/functions/blocks/kitchen_counter/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function kitcraft:blocks/kitchen_counter/place/detect
function kitcraft:blocks/kitchen_counter/destroy
execute as @e[tag=kitcraft_kitchen_counter] at @s run function #kitcraft:kitchen_counter_recipes
