#######
# Compiled from kitcraft/functions/blocks/kitchen_counter.mcscript
# to .//data/kitcraft/functions/blocks/kitchen_counter/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function kitcraft:blocks/kitchen_counter/place/detect
execute as @e[tag=kitcraft_kitchen_counter] at @s run function #kitcraft:kitchen_counter_recipes
execute as @e[tag=kitcraft_kitchen_counter] at @s run function kitcraft:blocks/kitchen_counter/fix_slots/main
execute as @e[tag=kitcraft_kitchen_counter] at @s run function kitcraft:blocks/kitchen_counter/trash_can/main
execute as @e[tag=kitcraft_kitchen_counter] at @s run function kitcraft:blocks/kitchen_counter/sink/main
function kitcraft:blocks/kitchen_counter/destroy
