#######
# Compiled from kitcraft/functions/blocks/kitchen_counter.mcscript
# to .//data/kitcraft/functions/blocks/kitchen_counter/craft/2.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @e[tag=kitcraft_oven] at @s if block ~ ~ ~ minecraft:furnace{Items:[{Slot:0b,id:"minecraft:crafting_table"}]} unless block ~ ~ ~ minecraft:furnace{Items:[{Slot:0b,tag:{kitcraft:{Cookable:1}}}]} run data modify block ~ ~ ~ Items[{Slot:0b}].tag.kitcraft.Cookable set value 1
