#######
# Compiled from kitcraft/functions/blocks/cutting_board.mcscript
# to .//data/kitcraft/functions/blocks/cutting_board/destroy/destroy.mcfunction
#
# Generated by Minecraft Script for 1.13
######
summon item ~ ~ ~ {Item:{id:"minecraft:armor_stand",Count:1b,tag:{kitcraft:{id:"cutting_board_place"},CustomModelData:705102,display:{Name:"{\"text\":\"Cutting Board\",\"italic\":\"false\"}",Lore:["{\"text\":\"Right-click to place\",\"italic\":\"false\",\"color\":\"dark_green\"}"]},EntityTag:{NoGravity:1b,Invulnerable:1b,Small:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,Tags:["kitcraft_cutting_board","kitcraft_cutting_board_init"]}}}}
kill @e[type=armor_stand,tag=kitcraft_cutting_board_vis,distance=..2,limit=1,sort=nearest]
kill @s
