#######
# Compiled from kitcraft/functions/blocks/cutting_board.mcscript
# to .//data/kitcraft/functions/blocks/cutting_board/destroy/detect.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @e[type=armor_stand,tag=kitcraft_cutting_board] at @s if entity @e[distance=..1,type=item,nbt={OnGround:1b,Item:{id:"minecraft:tnt"}}] run function kitcraft:blocks/cutting_board/destroy/destroy
