#######
# Compiled from kitcraft/functions/blocks/trash_can.mcscript
# to .//data/kitcraft/functions/blocks/trash_can/fix_slots/2.mcfunction
#
# Generated by Minecraft Script for 1.13
######
summon item ^ ^ ^1 {Item:{id:"minecraft:arrow",Count:1b}}
execute positioned ^ ^ ^1 run data modify entity @e[type=item,limit=1,sort=nearest] Item.id set from block ^ ^ ^-1 Items[{Slot:2b}].id
execute positioned ^ ^ ^1 run data modify entity @e[type=item,limit=1,sort=nearest] Item.Count set from block ^ ^ ^-1 Items[{Slot:2b}].Count
execute positioned ^ ^ ^1 run data modify entity @e[type=item,limit=1,sort=nearest] Item.tag set from block ^ ^ ^-1 Items[{Slot:2b}].tag
replaceitem block ~ ~ ~ container.2 minecraft:light_gray_stained_glass_pane{display:{Name:"{\"text\":\"\"}"},Placeholder:1}
