#######
# Compiled from kitcraft/functions/blocks/trash_can.mcscript
# to .//data/kitcraft/functions/blocks/trash_can/fix_slots/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute unless data block ~ ~ ~ Items[{Slot:1b}].tag.Placeholder if block ~ ~ ~ minecraft:hopper{Items:[{Slot:1b}]} run function kitcraft:blocks/trash_can/fix_slots/1

execute unless data block ~ ~ ~ Items[{Slot:2b}].tag.Placeholder if block ~ ~ ~ minecraft:hopper{Items:[{Slot:2b}]} run function kitcraft:blocks/trash_can/fix_slots/2

execute unless data block ~ ~ ~ Items[{Slot:3b}].tag.Placeholder if block ~ ~ ~ minecraft:hopper{Items:[{Slot:3b}]} run function kitcraft:blocks/trash_can/fix_slots/3

