#######
# Compiled from data/kitcraft/functions/creative_menu.mcscript
# to .//data/kitcraft/functions/creative_menu/food.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tellraw @s {"text":""}
tellraw @s {"text":""}
tellraw @s [{"text":"<===== ","color":"aqua"},{"translate":"Kitcraft Creative Menu (Food)","color":"red"},{"text":" =====>","color":"aqua"}]
tellraw @s {"text":""}
#Fries
tellraw @s [{"text":"► ["},{"text":"1","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s kc_c_menu_f 11"}},{"text":"] [","color":"reset"},{"text":"64","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s kc_c_menu_f 21"}},{"text":"] ","color":"reset"},{"translate":"Fries"}]
#Tasty TNT
tellraw @s [{"text":"► ["},{"text":"1","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s kc_c_menu_f 12"}},{"text":"] [","color":"reset"},{"text":"64","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s kc_c_menu_f 22"}},{"text":"] ","color":"reset"},{"translate":"Tasty TNT"}]
#Ender Cookie
tellraw @s [{"text":"► ["},{"text":"1","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s kc_c_menu_f 13"}},{"text":"] [","color":"reset"},{"text":"64","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s kc_c_menu_f 23"}},{"text":"] ","color":"reset"},{"translate":"Ender Cookie"}]
#Lemon Soda
tellraw @s [{"text":"► ["},{"text":"1","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s kc_c_menu_f 14"}},{"text":"] [","color":"reset"},{"text":"64","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s kc_c_menu_f 24"}},{"text":"] ","color":"reset"},{"translate":"Lemon Soda"}]
tellraw @s {"text":""}
tellraw @s {"text":""}
