#######
# Compiled from data/kitcraft/functions/creative_menu.mcscript
# to .//data/kitcraft/functions/creative_menu/menu.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tellraw @s {"text":""}
tellraw @s {"text":""}
tellraw @s [{"text":"<===== ","color":"aqua"},{"translate":"Kitcraft Creative Menu","color":"red"},{"text":" =====>","color":"aqua"}]
#Cutting Board
tellraw @s {"text":""}
tellraw @s {"text":""}