#######
# Compiled from data/kitcraft/functions/creative_menu.mcscript
# to .//data/kitcraft/functions/creative_menu/misc.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tellraw @s {"text":""}
tellraw @s {"text":""}
tellraw @s [{"text":"<===== ","color":"aqua"},{"translate":"Kitcraft Creative Menu (Misc)","color":"red"},{"text":" =====>","color":"aqua"}]
tellraw @s {"text":""}
#Cutting Board
tellraw @s [{"text":"► ["},{"text":"1","color":"green","clickEvent":{"action":"run_command","value":"/function kitcraft:give/blocks/cutting_board"}},{"text":"] ","color":"reset"},{"translate":"Cutting Board"}]
#Kitchen Counter
tellraw @s [{"text":"► ["},{"text":"1","color":"green","clickEvent":{"action":"run_command","value":"/function kitcraft:give/blocks/kitchen_counter"}},{"text":"] ","color":"reset"},{"translate":"Kitchen Counter"}]
#Oven
tellraw @s [{"text":"► ["},{"text":"1","color":"green","clickEvent":{"action":"run_command","value":"/function kitcraft:give/blocks/oven"}},{"text":"] ","color":"reset"},{"translate":"Oven"}]
#Sink
tellraw @s [{"text":"► ["},{"text":"1","color":"green","clickEvent":{"action":"run_command","value":"/function kitcraft:give/blocks/sink"}},{"text":"] ","color":"reset"},{"translate":"Sink"}]
#Trashcan
tellraw @p [{"text":"► ["},{"text":"1","color":"green","clickEvent":{"action":"run_command","value":"/function kitcraft:give/blocks/trash_can"}},{"text":"] ","color":"reset"},{"translate":"Trashcan"}]
tellraw @s {"text":""}
tellraw @s {"text":""}
