#######
# Compiled from data/kitcraft/functions/creative_menu.mcscript
# to .//data/kitcraft/functions/creative_menu/misc.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tellraw @s {"text":""}
tellraw @s {"text":""}
tellraw @s [{"text":"<===== ","color":"aqua"},{"translate":"Kitcraft Creative Menu (Misc)","color":"red"},{"text":" =====>","color":"aqua"}]
tellraw @s {"text":""}
tellraw @s [{"text":"<== ","color":"aqua"},{"translate":"Blocks","color":"red"},{"text":" ==>","color":"aqua"}]
#Cutting Board
tellraw @s [{"text":"► ["},{"text":"1","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s kc_c_menu_m 11"}},{"text":"] [","color":"reset"},{"text":"16","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s kc_c_menu_m 21"}},{"text":"] ","color":"reset"},{"translate":"Cutting Board"}]
#Crop Harvester
tellraw @s [{"text":"► ["},{"text":"1","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s kc_c_menu_m 17"}},{"text":"] [","color":"reset"},{"text":"16","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s kc_c_menu_m 27"}},{"text":"] ","color":"reset"},{"translate":"Crop Harvester"}]
#Fruit Picker
tellraw @s [{"text":"► ["},{"text":"1","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s kc_c_menu_m 18"}},{"text":"] [","color":"reset"},{"text":"16","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s kc_c_menu_m 28"}},{"text":"] ","color":"reset"},{"translate":"Fruit Picker"}]
#Kitchen Counter
tellraw @s [{"text":"► ["},{"text":"1","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s kc_c_menu_m 12"}},{"text":"] [","color":"reset"},{"text":"16","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s kc_c_menu_m 22"}},{"text":"] ","color":"reset"},{"translate":"Kitchen Counter"}]
#Oven
tellraw @s [{"text":"► ["},{"text":"1","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s kc_c_menu_m 13"}},{"text":"] [","color":"reset"},{"text":"16","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s kc_c_menu_m 23"}},{"text":"] ","color":"reset"},{"translate":"Oven"}]
#Sink
tellraw @s [{"text":"► ["},{"text":"1","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s kc_c_menu_m 14"}},{"text":"] [","color":"reset"},{"text":"16","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s kc_c_menu_m 24"}},{"text":"] ","color":"reset"},{"translate":"Sink"}]
#Trashcan
tellraw @s [{"text":"► ["},{"text":"1","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s kc_c_menu_m 15"}},{"text":"] [","color":"reset"},{"text":"16","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s kc_c_menu_m 25"}},{"text":"] ","color":"reset"},{"translate":"Trashcan"}]
#Kitchen Tile
#/tellraw @s [{"text":"► ["},{"text":"1","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s kc_c_menu_m 16"}},{"text":"] [","color":"reset"},{"text":"64","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s kc_c_menu_m 26"}},{"text":"] ","color":"reset"},{"translate":"Kitchen Tile"}]
tellraw @s {"text":""}
tellraw @s [{"text":"<== ","color":"aqua"},{"translate":"Misc","color":"red"},{"text":" ==>","color":"aqua"}]
#Lettuce Seeds
tellraw @s [{"text":"► ["},{"text":"1","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s kc_c_menu_m 120"}},{"text":"] [","color":"reset"},{"text":"64","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s kc_c_menu_m 220"}},{"text":"] ","color":"reset"},{"translate":"Lettuce Seeds"}]
#Lemon Tree Sapling
tellraw @s [{"text":"► ["},{"text":"1","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s kc_c_menu_m 121"}},{"text":"] [","color":"reset"},{"text":"16","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s kc_c_menu_m 221"}},{"text":"] ","color":"reset"},{"translate":"Lemon Tree Sapling"}]
tellraw @s {"text":""}
tellraw @s {"text":""}
