#######
# Compiled from data/kitcraft/functions/creative_menu.mcscript
# to .//data/kitcraft/functions/creative_menu/select.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tellraw @s [{"text":" ► ","color":"green"},{"text":"Kitcraft ","hoverEvent":{"action":"show_text","value":"Select"},"clickEvent":{"action":"run_command","value":"/function kitcraft:creative_menu/ingredients"}},{"translate":"Ingredients","hoverEvent":{"action":"show_text","value":"Select"},"clickEvent":{"action":"run_command","value":"/function kitcraft:creative_menu/ingredients"}}]
tellraw @s [{"text":" ► ","color":"green"},{"text":"Kitcraft ","hoverEvent":{"action":"show_text","value":"Select"},"clickEvent":{"action":"run_command","value":"/function kitcraft:creative_menu/food"}},{"translate":"Food","hoverEvent":{"action":"show_text","value":"Select"},"clickEvent":{"action":"run_command","value":"/function kitcraft:creative_menu/food"}}]
tellraw @s [{"text":" ► ","color":"green"},{"text":"Kitcraft ","hoverEvent":{"action":"show_text","value":"Select"},"clickEvent":{"action":"run_command","value":"/function kitcraft:creative_menu/misc"}},{"translate":"Misc","hoverEvent":{"action":"show_text","value":"Select"},"clickEvent":{"action":"run_command","value":"/function kitcraft:creative_menu/misc"}}]
