#######
# Compiled from kitcraft/functions/blocks/kitchen_counter.mcscript
# to .//data/kitcraft/functions/blocks/kitchen_counter/recipes/tasty_tnt/1.mcfunction
#
# Generated by Minecraft Script for 1.13
######
replaceitem block ~ ~ ~ container.15 minecraft:tnt{kitcraft:{id:"tasty_tnt",NoPlacing:1,Eatable:1,sat:0,particle:"red",EatNoHunger:1},display:{Name:"{\"translate\":\"Tasty TNT\",\"italic\":false}",Lore:["{\"translate\":\"Press shift while holding to eat\",\"color\":\"dark_green\",\"italic\":false}"]}} 1
tag @s add kitcraft_kitchen_counter_crafted
tag @s add kitcraft_kitchen_counter_crafted_tasty_tnt
