#######
# Compiled from kitcraft/functions/blocks/kitchen_counter.mcscript
# to .//data/kitcraft/functions/blocks/kitchen_counter/recipes/dough.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if block ~ ~ ~ minecraft:dropper{Items:[{Slot: 0b, id: "minecraft:dead_bubble_coral", Count: 1b, tag: {kitcraft: {id: "flour"}}}, {Slot: 1b, id: "minecraft:dead_bubble_coral", Count: 1b, tag: {kitcraft: {id: "salt"}}}, {Slot: 3b, id: "minecraft:water_bucket", Count: 1b}]} unless block ~ ~ ~ minecraft:dropper{Items:[{Slot: 2b}]} unless block ~ ~ ~ minecraft:dropper{Items:[{Slot: 4b}]} unless block ~ ~ ~ minecraft:dropper{Items:[{Slot: 5b}]} unless block ~ ~ ~ minecraft:dropper{Items:[{Slot: 6b}]} unless block ~ ~ ~ minecraft:dropper{Items:[{Slot: 7b}]} unless block ~ ~ ~ minecraft:dropper{Items:[{Slot: 8b}]} run data merge block ~ ~ ~ {Items: [{Slot: 3b, id: "minecraft:bucket", Count: 1b}, {Slot: 0b, id: "minecraft:dead_bubble_coral", Count: 1b, tag: {CustomModelData: 7050006, display: {Name: "{\"translate\":\"Dough\",\"italic\":false}"}, kitcraft: {Cookable:1,id: "dough", NoPlacing: 1}}}]}

