#######
# Compiled from kitcraft/functions/blocks/kitchen_counter.mcscript
# to .//data/kitcraft/functions/blocks/kitchen_counter/recipes/tasty_tnt.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if block ~ ~ ~ minecraft:dropper{Items:[{Slot: 0b, id: "minecraft:bread", Count: 1b}, {Slot: 3b, id: "minecraft:tnt", Count: 1b}, {Slot: 6b, id: "minecraft:bread", Count: 1b}]} unless block ~ ~ ~ minecraft:dropper{Items:[{Slot: 1b}]} unless block ~ ~ ~ minecraft:dropper{Items:[{Slot: 2b}]} unless block ~ ~ ~ minecraft:dropper{Items:[{Slot: 4b}]} unless block ~ ~ ~ minecraft:dropper{Items:[{Slot: 5b}]} unless block ~ ~ ~ minecraft:dropper{Items:[{Slot: 7b}]} unless block ~ ~ ~ minecraft:dropper{Items:[{Slot: 8b}]} run data merge block ~ ~ ~ {Items: [{Slot:3b,id:"minecraft:tnt",Count:1b,tag:{kitcraft:{id:"tasty_tnt",NoPlacing:1,Eatable:1,sat:0,particle:"red",EatNoHunger:1},display:{Name:"{\"translate\":\"Tasty TNT\",\"italic\":false}",Lore:["{\"translate\":\"Press shift while holding to eat\",\"color\":\"dark_green\",\"italic\":false}"]}}}]}
