#######
# Compiled from kitcraft/functions/blocks/oven.mcscript
# to .//data/kitcraft/functions/blocks/oven/cooking/time_main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if entity @s[scores={kc_burntime=1..}] if block ~ ~ ~ minecraft:furnace{Items:[{Slot:0b,tag:{kitcraft:{Cookable:1}}}]} run function kitcraft:blocks/oven/cooking/time

execute unless block ~ ~ ~ minecraft:furnace{Items:[{Slot:0b,tag:{kitcraft:{Cookable:1}}}]} run scoreboard players reset @s kc_cooktime_set

