#######
# Compiled from data/kitcraft/functions/give.mcscript
# to .//data/kitcraft/functions/give/kitchen_tile.mcfunction
#
# Generated by Minecraft Script for 1.13
######
give @s firework_rocket{CustomModelData:7050001,kitcraftBlock:1}
