#######
# Compiled from kitcraft/functions/blocks/crop_harvester.mcscript
# to .//data/kitcraft/functions/blocks/crop_harvester/schedule/a.mcfunction
#
# Generated by Minecraft Script for 1.13
######
schedule function kitcraft:blocks/crop_harvester/schedule/b 10s
execute as @e[tag=kitcraft_crop_harvester] at @s run function kitcraft:blocks/crop_harvester/harvest
