#######
# Compiled from data/kitcraft/functions/smash_lib.mcscript
# to .//data/kitcraft/functions/smash_lib/recipes.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function kitcraft:smash_lib/recipes/flour
