#######
# Compiled from kitcraft/functions/blocks/kitchen_counter.mcscript
# to .//data/kitcraft/functions/blocks/kitchen_counter/recipes/ender_cookie/2.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function kitcraft:blocks/kitchen_counter/crafted
tag @s remove kitcraft_kitchen_counter_crafted
tag @s remove kitcraft_kitchen_counter_crafted_ender_cookie
