#######
# Compiled from kitcraft/functions/blocks/kitchen_counter.mcscript
# to .//data/kitcraft/functions/blocks/kitchen_counter/recipes/lemon_juice/1.mcfunction
#
# Generated by Minecraft Script for 1.13
######
replaceitem block ~ ~ ~ container.15 minecraft:dead_bubble_coral{display:{Name:"{\"translate\":\"Lemon Juice\",\"italic\":false}"},CustomModelData:7052001,kitcraft:{id:"lemon_juice",NoPlacing:1b,containerItem:"bottle"}} 1
tag @s add kitcraft_kitchen_counter_crafted
tag @s add kitcraft_kitchen_counter_crafted_lemon_juice
