#######
# Compiled from kitcraft/functions/crops/lemon_tree.mcscript
# to .//data/kitcraft/functions/crops/lemon_tree/destroy.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @e[type=armor_stand,tag=kitcraft_lemon_tree_base,tag=!kitcraft_lemon_tree_detect_growing] at @s unless block ~ ~ ~ minecraft:jungle_log run function kitcraft:crops/lemon_tree/destroy_tree
execute as @e[type=armor_stand,tag=kitcraft_lemon_tree_base,tag=!kitcraft_lemon_tree_detect_growing] at @s unless block ~ ~ ~ minecraft:jungle_log run kill @s
execute as @e[type=armor_stand,tag=kitcraft_lemon_tree,tag=kitcraft_lemon_tree_detect_growing] at @s unless block ~ ~ ~ minecraft:jungle_sapling unless block ~ ~ ~ minecraft:jungle_log run kill @s[type=armor_stand]
execute as @e[type=armor_stand,tag=kitcraft_lemon_tree,tag=kitcraft_lemon_tree_detect_growing,limit=1,sort=random] at @s if entity @e[type=armor_stand,tag=kitcraft_lemon_tree,tag=!kitcraft_lemon_tree_growing,distance=.1..2] run kill @s
execute as @e[type=armor_stand,tag=kitcraft_lemon_tree_fruit] at @s align y unless block ~ ~1 ~ minecraft:jungle_leaves run function kitcraft:crops/lemon_tree/fruit/destroy
execute as @e[type=armor_stand,tag=kitcraft_lemon_tree_fruit] at @s unless entity @e[type=armor_stand,tag=kitcraft_lemon_tree,distance=..50] run function kitcraft:crops/lemon_tree/fruit/destroy
execute as @e[type=armor_stand,tag=kitcraft_lemon_tree_fruit_vis] at @s unless entity @e[type=armor_stand,tag=kitcraft_lemon_tree_fruit,distance=...5] run kill @s[type=armor_stand]
