#######
# Compiled from kitcraft/functions/crops/lemon_tree.mcscript
# to .//data/kitcraft/functions/crops/lemon_tree/destroy_tree.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if block ~ ~ ~ minecraft:jungle_log run setblock ~ ~ ~ air destroy

execute if block ~ ~ ~ minecraft:jungle_leaves run scoreboard players set @p kc_random_range 32
execute if block ~ ~ ~ minecraft:jungle_leaves run function kitcraft:random/main
execute if block ~ ~ ~ minecraft:jungle_leaves if score @p kc_random matches 1 run summon item ~ ~ ~ {Item:{id:"minecraft:armor_stand",Count:1b,tag:{CustomModelData:7051001,display:{Lore:["{\"translate\":\"Right-click to place\",\"italic\":\"false\",\"color\":\"dark_green\"}"],Name:"{\"translate\":\"Lemon Tree Sapling\",\"italic\":\"false\"}"},EntityTag:{NoGravity:1b,Small:1b,Invulnerable:1b,PersistenceRequired:1b,Marker:1b,Invisible:1b,id:"minecraft:armor_stand",Tags:["kitcraft_lemon_tree","kitcraft_lemon_tree_init"]},kitcraft:{id: "lemon_tree_sapling"}}}}
execute if block ~ ~ ~ minecraft:jungle_leaves run scoreboard players reset @p kc_random
execute if block ~ ~ ~ minecraft:jungle_leaves run setblock ~ ~ ~ air replace

execute positioned ~1 ~ ~ if block ~ ~ ~ minecraft:jungle_log run function kitcraft:crops/lemon_tree/destroy_tree
execute positioned ~-1 ~ ~ if block ~ ~ ~ minecraft:jungle_log run function kitcraft:crops/lemon_tree/destroy_tree
execute positioned ~ ~1 ~ if block ~ ~ ~ minecraft:jungle_log run function kitcraft:crops/lemon_tree/destroy_tree
execute positioned ~ ~-1 ~ if block ~ ~ ~ minecraft:jungle_log run function kitcraft:crops/lemon_tree/destroy_tree
execute positioned ~ ~ ~1 if block ~ ~ ~ minecraft:jungle_log run function kitcraft:crops/lemon_tree/destroy_tree
execute positioned ~ ~ ~-1 if block ~ ~ ~ minecraft:jungle_log run function kitcraft:crops/lemon_tree/destroy_tree
execute positioned ~1 ~ ~1 if block ~ ~ ~ minecraft:jungle_log run function kitcraft:crops/lemon_tree/destroy_tree
execute positioned ~-1 ~ ~1 if block ~ ~ ~ minecraft:jungle_log run function kitcraft:crops/lemon_tree/destroy_tree
execute positioned ~1 ~ ~-1 if block ~ ~ ~ minecraft:jungle_log run function kitcraft:crops/lemon_tree/destroy_tree
execute positioned ~-1 ~ ~-1 if block ~ ~ ~ minecraft:jungle_log run function kitcraft:crops/lemon_tree/destroy_tree
execute positioned ~1 ~ ~ if block ~ ~ ~ minecraft:jungle_leaves run function kitcraft:crops/lemon_tree/destroy_tree
execute positioned ~-1 ~ ~ if block ~ ~ ~ minecraft:jungle_leaves run function kitcraft:crops/lemon_tree/destroy_tree
execute positioned ~ ~1 ~ if block ~ ~ ~ minecraft:jungle_leaves run function kitcraft:crops/lemon_tree/destroy_tree
execute positioned ~ ~-1 ~ if block ~ ~ ~ minecraft:jungle_leaves run function kitcraft:crops/lemon_tree/destroy_tree
execute positioned ~ ~ ~1 if block ~ ~ ~ minecraft:jungle_leaves run function kitcraft:crops/lemon_tree/destroy_tree
execute positioned ~ ~ ~-1 if block ~ ~ ~ minecraft:jungle_leaves run function kitcraft:crops/lemon_tree/destroy_tree
execute positioned ~1 ~ ~1 if block ~ ~ ~ minecraft:jungle_leaves run function kitcraft:crops/lemon_tree/destroy_tree
execute positioned ~-1 ~ ~1 if block ~ ~ ~ minecraft:jungle_leaves run function kitcraft:crops/lemon_tree/destroy_tree
execute positioned ~1 ~ ~-1 if block ~ ~ ~ minecraft:jungle_leaves run function kitcraft:crops/lemon_tree/destroy_tree
execute positioned ~-1 ~ ~-1 if block ~ ~ ~ minecraft:jungle_leaves run function kitcraft:crops/lemon_tree/destroy_tree
