#######
# Compiled from kitcraft/functions/crops/lemon_tree.mcscript
# to .//data/kitcraft/functions/crops/lemon_tree/detect_base.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tag @s add kitcraft_lemon_tree_base
execute unless entity @e[type=armor_stand,tag=kitcraft_lemon_tree,distance=...5] run summon minecraft:armor_stand ~ ~ ~ {NoGravity:1b,Small:1b,Invulnerable:1b,PersistenceRequired:1b,Marker:1b,Invisible:1b,Tags:["kitcraft_lemon_tree_base"]}

execute positioned ~1 ~ ~ if block ~ ~ ~ minecraft:jungle_log unless entity @e[type=armor_stand,tag=kitcraft_lemon_tree_base,distance=...5] run function kitcraft:crops/lemon_tree/detect_base
execute positioned ~-1 ~ ~ if block ~ ~ ~ minecraft:jungle_log unless entity @e[type=armor_stand,tag=kitcraft_lemon_tree_base,distance=...5] run function kitcraft:crops/lemon_tree/detect_base
execute positioned ~ ~ ~1 if block ~ ~ ~ minecraft:jungle_log unless entity @e[type=armor_stand,tag=kitcraft_lemon_tree_base,distance=...5] run function kitcraft:crops/lemon_tree/detect_base
execute positioned ~ ~ ~-1 if block ~ ~ ~ minecraft:jungle_log unless entity @e[type=armor_stand,tag=kitcraft_lemon_tree_base,distance=...5] run function kitcraft:crops/lemon_tree/detect_base
