#######
# Compiled from kitcraft/functions/crops/lemon_tree.mcscript
# to .//data/kitcraft/functions/crops/lemon_tree/grow_detect.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if block ~ ~ ~ minecraft:jungle_log run tag @s remove kitcraft_lemon_tree_detect_growing
execute if block ~ ~ ~ minecraft:jungle_log run function kitcraft:crops/lemon_tree/detect_base
execute if block ~ ~ ~ minecraft:jungle_log run tag @s add kitcraft_lemon_tree_grow_fruits
execute if block ~ ~ ~ minecraft:jungle_log align xyz positioned ~.5 ~.5 ~.5 run function kitcraft:crops/lemon_tree/grow

