#######
# Compiled from kitcraft/functions/crops/lemon_tree.mcscript
# to .//data/kitcraft/functions/crops/lemon_tree/grow.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if block ~ ~-1 ~ air if block ~1 ~ ~ minecraft:jungle_leaves if block ~-1 ~ ~ minecraft:jungle_leaves if block ~ ~ ~1 minecraft:jungle_leaves if block ~ ~ ~-1 minecraft:jungle_leaves run summon armor_stand ~ ~ ~ {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["kitcraft_lemon_tree_fruit_init"]}
execute if block ~ ~-1 ~ air if block ~1 ~ ~ minecraft:jungle_log if block ~-1 ~ ~ minecraft:jungle_leaves if block ~ ~ ~1 minecraft:jungle_leaves if block ~ ~ ~-1 minecraft:jungle_leaves run summon armor_stand ~ ~ ~ {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["kitcraft_lemon_tree_fruit_init"]}
execute if block ~ ~-1 ~ air if block ~1 ~ ~ minecraft:jungle_leaves if block ~-1 ~ ~ minecraft:jungle_log if block ~ ~ ~1 minecraft:jungle_leaves if block ~ ~ ~-1 minecraft:jungle_leaves run summon armor_stand ~ ~ ~ {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["kitcraft_lemon_tree_fruit_init"]}
execute if block ~ ~-1 ~ air if block ~1 ~ ~ minecraft:jungle_log if block ~-1 ~ ~ minecraft:jungle_log if block ~ ~ ~1 minecraft:jungle_leaves if block ~ ~ ~-1 minecraft:jungle_leaves run summon armor_stand ~ ~ ~ {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["kitcraft_lemon_tree_fruit_init"]}
execute if block ~ ~-1 ~ air if block ~1 ~ ~ minecraft:jungle_leaves if block ~-1 ~ ~ minecraft:jungle_leaves if block ~ ~ ~1 minecraft:jungle_log if block ~ ~ ~-1 minecraft:jungle_leaves run summon armor_stand ~ ~ ~ {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["kitcraft_lemon_tree_fruit_init"]}
execute if block ~ ~-1 ~ air if block ~1 ~ ~ minecraft:jungle_log if block ~-1 ~ ~ minecraft:jungle_leaves if block ~ ~ ~1 minecraft:jungle_log if block ~ ~ ~-1 minecraft:jungle_leaves run summon armor_stand ~ ~ ~ {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["kitcraft_lemon_tree_fruit_init"]}
execute if block ~ ~-1 ~ air if block ~1 ~ ~ minecraft:jungle_leaves if block ~-1 ~ ~ minecraft:jungle_log if block ~ ~ ~1 minecraft:jungle_log if block ~ ~ ~-1 minecraft:jungle_leaves run summon armor_stand ~ ~ ~ {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["kitcraft_lemon_tree_fruit_init"]}
execute if block ~ ~-1 ~ air if block ~1 ~ ~ minecraft:jungle_log if block ~-1 ~ ~ minecraft:jungle_log if block ~ ~ ~1 minecraft:jungle_log if block ~ ~ ~-1 minecraft:jungle_leaves run summon armor_stand ~ ~ ~ {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["kitcraft_lemon_tree_fruit_init"]}
execute if block ~ ~-1 ~ air if block ~1 ~ ~ minecraft:jungle_leaves if block ~-1 ~ ~ minecraft:jungle_leaves if block ~ ~ ~1 minecraft:jungle_leaves if block ~ ~ ~-1 minecraft:jungle_log run summon armor_stand ~ ~ ~ {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["kitcraft_lemon_tree_fruit_init"]}
execute if block ~ ~-1 ~ air if block ~1 ~ ~ minecraft:jungle_log if block ~-1 ~ ~ minecraft:jungle_leaves if block ~ ~ ~1 minecraft:jungle_leaves if block ~ ~ ~-1 minecraft:jungle_log run summon armor_stand ~ ~ ~ {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["kitcraft_lemon_tree_fruit_init"]}
execute if block ~ ~-1 ~ air if block ~1 ~ ~ minecraft:jungle_leaves if block ~-1 ~ ~ minecraft:jungle_log if block ~ ~ ~1 minecraft:jungle_leaves if block ~ ~ ~-1 minecraft:jungle_log run summon armor_stand ~ ~ ~ {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["kitcraft_lemon_tree_fruit_init"]}
execute if block ~ ~-1 ~ air if block ~1 ~ ~ minecraft:jungle_log if block ~-1 ~ ~ minecraft:jungle_log if block ~ ~ ~1 minecraft:jungle_leaves if block ~ ~ ~-1 minecraft:jungle_log run summon armor_stand ~ ~ ~ {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["kitcraft_lemon_tree_fruit_init"]}
execute if block ~ ~-1 ~ air if block ~1 ~ ~ minecraft:jungle_leaves if block ~-1 ~ ~ minecraft:jungle_leaves if block ~ ~ ~1 minecraft:jungle_log if block ~ ~ ~-1 minecraft:jungle_log run summon armor_stand ~ ~ ~ {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["kitcraft_lemon_tree_fruit_init"]}
execute if block ~ ~-1 ~ air if block ~1 ~ ~ minecraft:jungle_log if block ~-1 ~ ~ minecraft:jungle_leaves if block ~ ~ ~1 minecraft:jungle_log if block ~ ~ ~-1 minecraft:jungle_log run summon armor_stand ~ ~ ~ {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["kitcraft_lemon_tree_fruit_init"]}
execute if block ~ ~-1 ~ air if block ~1 ~ ~ minecraft:jungle_leaves if block ~-1 ~ ~ minecraft:jungle_log if block ~ ~ ~1 minecraft:jungle_log if block ~ ~ ~-1 minecraft:jungle_log run summon armor_stand ~ ~ ~ {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["kitcraft_lemon_tree_fruit_init"]}
execute if block ~ ~-1 ~ air if block ~1 ~ ~ minecraft:jungle_log if block ~-1 ~ ~ minecraft:jungle_log if block ~ ~ ~1 minecraft:jungle_log if block ~ ~ ~-1 minecraft:jungle_log run summon armor_stand ~ ~ ~ {NoGravity:1b,Invisible:1b,Marker:1b,Tags:["kitcraft_lemon_tree_fruit_init"]}

#GO ON
execute align xz run summon area_effect_cloud ~.5 ~ ~.5 {NoGravity:1b,Radius:0.1f,Duration:0,Tags:["kitcraft_tree_detect"]}
execute positioned ~1 ~ ~ if block ~ ~ ~ minecraft:jungle_log unless entity @e[type=area_effect_cloud,distance=...75,tag=kitcraft_tree_detect] run function kitcraft:crops/lemon_tree/grow
execute positioned ~-1 ~ ~ if block ~ ~ ~ minecraft:jungle_log unless entity @e[type=area_effect_cloud,distance=...75,tag=kitcraft_tree_detect] run function kitcraft:crops/lemon_tree/grow
execute positioned ~ ~1 ~ if block ~ ~ ~ minecraft:jungle_log unless entity @e[type=area_effect_cloud,distance=...75,tag=kitcraft_tree_detect] run function kitcraft:crops/lemon_tree/grow
execute positioned ~ ~ ~1 if block ~ ~ ~ minecraft:jungle_log unless entity @e[type=area_effect_cloud,distance=...75,tag=kitcraft_tree_detect] run function kitcraft:crops/lemon_tree/grow
execute positioned ~ ~ ~-1 if block ~ ~ ~ minecraft:jungle_log unless entity @e[type=area_effect_cloud,distance=...75,tag=kitcraft_tree_detect] run function kitcraft:crops/lemon_tree/grow
execute positioned ~1 ~ ~1 if block ~ ~ ~ minecraft:jungle_log unless entity @e[type=area_effect_cloud,distance=...75,tag=kitcraft_tree_detect] run function kitcraft:crops/lemon_tree/grow
execute positioned ~-1 ~ ~1 if block ~ ~ ~ minecraft:jungle_log unless entity @e[type=area_effect_cloud,distance=...75,tag=kitcraft_tree_detect] run function kitcraft:crops/lemon_tree/grow
execute positioned ~1 ~ ~-1 if block ~ ~ ~ minecraft:jungle_log unless entity @e[type=area_effect_cloud,distance=...75,tag=kitcraft_tree_detect] run function kitcraft:crops/lemon_tree/grow
execute positioned ~-1 ~ ~-1 if block ~ ~ ~ minecraft:jungle_log unless entity @e[type=area_effect_cloud,distance=...75,tag=kitcraft_tree_detect] run function kitcraft:crops/lemon_tree/grow
execute positioned ~1 ~ ~ if block ~ ~ ~ minecraft:jungle_leaves unless entity @e[type=area_effect_cloud,distance=...75,tag=kitcraft_tree_detect] run function kitcraft:crops/lemon_tree/grow
execute positioned ~-1 ~ ~ if block ~ ~ ~ minecraft:jungle_leaves unless entity @e[type=area_effect_cloud,distance=...75,tag=kitcraft_tree_detect] run function kitcraft:crops/lemon_tree/grow
execute positioned ~ ~1 ~ if block ~ ~ ~ minecraft:jungle_leaves unless entity @e[type=area_effect_cloud,distance=...75,tag=kitcraft_tree_detect] run function kitcraft:crops/lemon_tree/grow
execute positioned ~ ~ ~1 if block ~ ~ ~ minecraft:jungle_leaves unless entity @e[type=area_effect_cloud,distance=...75,tag=kitcraft_tree_detect] run function kitcraft:crops/lemon_tree/grow
execute positioned ~ ~ ~-1 if block ~ ~ ~ minecraft:jungle_leaves unless entity @e[type=area_effect_cloud,distance=...75,tag=kitcraft_tree_detect] run function kitcraft:crops/lemon_tree/grow
execute positioned ~1 ~ ~1 if block ~ ~ ~ minecraft:jungle_leaves unless entity @e[type=area_effect_cloud,distance=...75,tag=kitcraft_tree_detect] run function kitcraft:crops/lemon_tree/grow
execute positioned ~-1 ~ ~1 if block ~ ~ ~ minecraft:jungle_leaves unless entity @e[type=area_effect_cloud,distance=...75,tag=kitcraft_tree_detect] run function kitcraft:crops/lemon_tree/grow
execute positioned ~1 ~ ~-1 if block ~ ~ ~ minecraft:jungle_leaves unless entity @e[type=area_effect_cloud,distance=...75,tag=kitcraft_tree_detect] run function kitcraft:crops/lemon_tree/grow
execute positioned ~-1 ~ ~-1 if block ~ ~ ~ minecraft:jungle_leaves unless entity @e[type=area_effect_cloud,distance=...75,tag=kitcraft_tree_detect] run function kitcraft:crops/lemon_tree/grow
