#######
# Compiled from kitcraft/functions/crops/lemon_tree.mcscript
# to .//data/kitcraft/functions/crops/lemon_tree/plant.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if block ~ ~-1 ~ #kitcraft:tree_plantable run setblock ~ ~ ~ minecraft:jungle_sapling
execute if block ~ ~-1 ~ #kitcraft:tree_plantable run tag @s remove kitcraft_lemon_tree_init
execute if block ~ ~-1 ~ #kitcraft:tree_plantable run tag @s add kitcraft_lemon_tree_detect_growing
execute unless block ~ ~-1 ~ #kitcraft:tree_plantable run summon item ~ ~ ~ {Item:{id:"minecraft:armor_stand",Count:1b,tag:{CustomModelData:7051001,display:{Lore:["{\"translate\":\"Right-click to place\",\"italic\":\"false\",\"color\":\"dark_green\"}"],Name:"{\"translate\":\"Lemon Tree Sapling\",\"italic\":\"false\"}"},EntityTag:{NoGravity:1b,Small:1b,Invulnerable:1b,PersistenceRequired:1b,Marker:1b,Invisible:1b,id:"minecraft:armor_stand",Tags:["kitcraft_lemon_tree","kitcraft_lemon_tree_init"]},kitcraft:{id: "lemon_tree_sapling"}}}}
execute unless block ~ ~-1 ~ #kitcraft:tree_plantable run kill @s[type=armor_stand]
