#######
# Compiled from kitcraft/functions/blocks/kitchen_counter.mcscript
# to .//data/kitcraft/functions/blocks/kitchen_counter/trash_can/disable.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tag @s remove kitcraft_kitchen_counter_trash_can
localDebug(Trashcan for kitchen counter deactivated)
