#######
# Compiled from kitcraft/functions/blocks/kitchen_counter.mcscript
# to .//data/kitcraft/functions/blocks/kitchen_counter/trash_can/enable.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tag @s add kitcraft_kitchen_counter_trash_can
replaceitem block ~ ~ ~ container.0 air
localDebug(Trashcan for kitchen counter activated)
