#######
# Compiled from kitcraft/functions/blocks/kitchen_counter.mcscript
# to .//data/kitcraft/functions/blocks/kitchen_counter/trash_can/function_detect.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if block ~ ~ ~ minecraft:barrel{Items:[{Slot:0b}]} run function kitcraft:blocks/kitchen_counter/trash_can/function

