#######
# Compiled from kitcraft/functions/blocks/kitchen_counter.mcscript
# to .//data/kitcraft/functions/blocks/kitchen_counter/trash_can/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if entity @s[tag=!kitcraft_kitchen_counter_trash_can] if entity @e[distance=..7.5,tag=kitcraft_trash_can] run function kitcraft:blocks/kitchen_counter/trash_can/enable

execute if entity @s[tag=kitcraft_kitchen_counter_trash_can] unless entity @e[distance=..7.5,tag=kitcraft_trash_can] run function kitcraft:blocks/kitchen_counter/trash_can/disable
execute if entity @s[tag=kitcraft_kitchen_counter_trash_can] run function kitcraft:blocks/kitchen_counter/trash_can/function_detect

