#######
# Compiled from kitcraft/functions/blocks/trash_can.mcscript
# to .//data/kitcraft/functions/blocks/trash_can/craft.mcfunction
#
# Generated by Minecraft Script for 1.13
######
advancement revoke @s only kitcraft:craft_trash_can_utility
recipe take @s kitcraft:trash_can
clear @s minecraft:structure_void 1
function kitcraft:give/blocks/trash_can
