#######
# Compiled from kitcraft/functions/blocks/trash_can.mcscript
# to .//data/kitcraft/functions/blocks/trash_can/functionality_block.mcfunction
#
# Generated by Minecraft Script for 1.13
######
replaceitem block ~ ~ ~ container.1 minecraft:light_gray_stained_glass_pane{display:{Name:"{\"text\":\"\"}"},Placeholder:1}
replaceitem block ~ ~ ~ container.2 minecraft:light_gray_stained_glass_pane{display:{Name:"{\"text\":\"\"}"},Placeholder:1}
replaceitem block ~ ~ ~ container.3 minecraft:light_gray_stained_glass_pane{display:{Name:"{\"text\":\"\"}"},Placeholder:1}
replaceitem block ~ ~ ~ container.4 arrow
data modify block ~ ~ ~ Items[4].id set from block ~ ~ ~ Items[0].id
data modify block ~ ~ ~ Items[4].Count set from block ~ ~ ~ Items[0].Count
data modify block ~ ~ ~ Items[4].tag set from block ~ ~ ~ Items[0].tag
replaceitem block ~ ~ ~ container.0 air
