#######
# Compiled from kitcraft/functions/blocks/trash_can.mcscript
# to .//data/kitcraft/functions/blocks/trash_can/functionality_item.mcfunction
#
# Generated by Minecraft Script for 1.13
######
replaceitem block ~ ~ ~ container.0 arrow
replaceitem block ~ ~ ~ container.1 minecraft:light_gray_stained_glass_pane{display:{Name:"{\"text\":\"\"}"},Placeholder:1}
replaceitem block ~ ~ ~ container.2 minecraft:light_gray_stained_glass_pane{display:{Name:"{\"text\":\"\"}"},Placeholder:1}
replaceitem block ~ ~ ~ container.3 minecraft:light_gray_stained_glass_pane{display:{Name:"{\"text\":\"\"}"},Placeholder:1}
replaceitem block ~ ~ ~ container.4 arrow
data modify block ~ ~ ~ Items[4].id set from entity @s Item.id
data modify block ~ ~ ~ Items[4].Count set from entity @s Item.Count
data modify block ~ ~ ~ Items[4].tag set from entity @s Item.tag
particle minecraft:dust 255 0 0 1 ~ ~.35 ~ 0.1 0 0.1 0 1
replaceitem block ~ ~ ~ container.0 air
kill @s