#######
# Compiled from kitcraft/functions/blocks/trash_can.mcscript
# to .//data/kitcraft/functions/blocks/trash_can/update_cooldown.mcfunction
#
# Generated by Minecraft Script for 1.13
######
data merge block ~ ~ ~ {TransferCooldown:1000000}
