#######
# Compiled from kitcraft/functions/blocks/kitchen_counter.mcscript
# to .//data/kitcraft/functions/blocks/kitchen_counter/recipes/salt/2.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function kitcraft:blocks/kitchen_counter/crafted
execute if entity @s[tag=!kitcraft_kitchen_counter_sink] run replaceitem block ~ ~ ~ container.2 minecraft:bucket
execute if entity @s[tag=!kitcraft_kitchen_counter_sink] run replaceitem block ~ ~ ~ container.3 minecraft:bucket
execute unless entity @s[tag=!kitcraft_kitchen_counter_sink] run replaceitem block ~ ~ ~ container.2 minecraft:water_bucket
execute unless entity @s[tag=!kitcraft_kitchen_counter_sink] run replaceitem block ~ ~ ~ container.3 minecraft:water_bucket
tag @s remove kitcraft_kitchen_counter_crafted
tag @s remove kitcraft_kitchen_counter_crafted_salt
