#######
# Compiled from data/kitcraft/functions/food.mcscript
# to .//data/kitcraft/functions/food/ender_cookie/read_functionality.mcfunction
#
# Generated by Minecraft Script for 1.13
######
summon armor_stand ~ ~ ~ {NoGravity:1b,Small:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,Tags:["kitcraft_ender_cookie_read"]}
execute at @e[type=minecraft:armor_stand,tag=kitcraft_ender_cookie_read,limit=1,sort=nearest] run function kitcraft:eating/food/ender_cookie/read_functionality_
