#######
# Compiled from kitcraft/functions/blocks/sink.mcscript
# to .//data/kitcraft/functions/blocks/sink/craft.mcfunction
#
# Generated by Minecraft Script for 1.13
######
advancement revoke @s only kitcraft:sink_utility
recipe take @s kitcraft:sink
clear @s minecraft:structure_void 1
scoreboard players set @s kc_c_menu_m 14
