#######
# Compiled from kitcraft/functions/blocks/sink.mcscript
# to .//data/kitcraft/functions/blocks/sink/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function kitcraft:blocks/sink/place/detect
function kitcraft:blocks/sink/destroy
function kitcraft:blocks/sink/maintain
function #kitcraft:sink_empty_item
