#######
# Compiled from data/kitcraft/functions/give.mcscript
# to .//data/kitcraft/functions/give/blocks/cutting_board.mcfunction
#
# Generated by Minecraft Script for 1.13
######
give @s minecraft:armor_stand{kitcraft:{id:"cutting_board_place"},CustomModelData:705102,display:{Name:"{\"translate\":\"Cutting Board\",\"italic\":\"false\"}",Lore:["{\"translate\":\"Right-click to place\",\"italic\":\"false\",\"color\":\"dark_green\"}"]},EntityTag:{NoGravity:1b,Invulnerable:1b,Small:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,Tags:["kitcraft_cutting_board","kitcraft_cutting_board_init"]}}
