#######
# Compiled from data/kitcraft/functions/give.mcscript
# to .//data/kitcraft/functions/give/blocks/kitchen_counter.mcfunction
#
# Generated by Minecraft Script for 1.13
######
give @s minecraft:armor_stand{kitcraft:{id:"kitchen_counter_place"},CustomModelData:705105,display:{Name:"{\"text\":\"Kitchen Counter\",\"italic\":\"false\"}",Lore:["{\"text\":\"Right-click to place\",\"italic\":\"false\",\"color\":\"dark_green\"}"]},EntityTag:{NoGravity:1b,Invulnerable:1b,Small:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,Tags:["kitcraft_kitchen_counter","kitcraft_kitchen_counter_init"]}}