#######
# Compiled from data/kitcraft/functions/give.mcscript
# to .//data/kitcraft/functions/give/blocks/oven.mcfunction
#
# Generated by Minecraft Script for 1.13
######
give @s minecraft:armor_stand{kitcraft:{id:"oven_place"},CustomModelData:705101,display:{Name:"{\"translate\":\"Oven\",\"italic\":\"false\"}",Lore:["{\"translate\":\"Right-click to place\",\"italic\":\"false\",\"color\":\"dark_green\"}"]},EntityTag:{NoGravity:1b,Invulnerable:1b,Small:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,Tags:["kitcraft_oven","kitcraft_oven_init"]}}
