#######
# Compiled from data/kitcraft/functions/give.mcscript
# to .//data/kitcraft/functions/give/blocks/sink.mcfunction
#
# Generated by Minecraft Script for 1.13
######
give @s minecraft:armor_stand{kitcraft:{id:"sink_place"},display:{Name:"{\"text\":\"Sink\",\"italic\":false}",Lore:["{\"text\":\"Right-click to place\",\"color\":\"dark_green\",\"italic\":false}"]},CustomModelData:705103,EntityTag:{NoGravity:1b,Invulnerable:1b,Small:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,Tags:["kitcraft_sink","kitcraft_sink_init"]}} 1
