#######
# Compiled from data/kitcraft/functions/give.mcscript
# to .//data/kitcraft/functions/give/blocks/trash_can.mcfunction
#
# Generated by Minecraft Script for 1.13
######
give @s minecraft:armor_stand{CustomModelData:705104,kitcraft:{id:"trash_can_place"},display:{Name:"{\"translate\":\"Trashcan\",\"italic\":\"false\"}",Lore:["{\"translate\":\"Right-click to place\",\"italic\":\"false\",\"color\":\"dark_green\"}"]},EntityTag:{NoGravity:1b,Invulnerable:1b,Small:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,Tags:["kitcraft_trash_can","kitcraft_trash_can_init"]}}
