#######
# Compiled from kitcraft/functions/blocks/fruit_picker.mcscript
# to .//data/kitcraft/functions/blocks/fruit_picker/place/place.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tag @s remove kitcraft_fruit_picker_init
setblock ~ ~ ~ dirt
execute align xyz run summon armor_stand ~0.5 ~0.5 ~0.5 {Tags: ["kitcraft_fruit_picker_vis"],Invisible:1,Marker:1,NoGravity:1,ArmorItems:[{},{},{},{id:"minecraft:armor_stand",Count:1b,tag:{CustomModelData:705107}}]}
