#######
# Compiled from kitcraft/functions/blocks/kitchen_tile.mcscript
# to .//data/kitcraft/functions/blocks/kitchen_tile/place/detect.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @s[nbt={FireworksItem:{tag:{CustomModelData:7050001}}}] run function kitcraft:blocks/kitchen_tile/place/place
kill @s
