#######
# Compiled from kitcraft/functions/blocks/kitchen_tile.mcscript
# to .//data/kitcraft/functions/blocks/kitchen_tile/place/place.mcfunction
#
# Generated by Minecraft Script for 1.13
######
setblock ~ ~ ~ minecraft:quartz_block
summon armor_stand ~0.5 ~0.5 ~0.5 {Tags: [isCustomBlock,kitcraft_kitchen_tile,newBlock],Invisible:1,Marker:1,NoGravity:1}
execute as @e[tag=kitcraft_kitchen_tile,tag=newBlock] run replaceitem entity @s armor.head minecraft:firework_rocket{CustomModelData:7050001}
execute as @e[tag=kitcraft_kitchen_tile,tag=newBlock] run tag @s remove newBlock