#######
# Compiled from kitcraft/functions/blocks/oven.mcscript
# to .//data/kitcraft/functions/blocks/oven/fuel/remove.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard players operation @s kc_slot_fuel -= 1 kc_numbers

#Item[1]
execute store result score @s kc_slot run data get block ~ ~ ~ Items[1].Slot
execute if score @s kc_slot matches 1 store result block ~ ~ ~ Items[1].Count short 1 run scoreboard players get @s kc_slot_fuel

scoreboard players reset @s kc_slot

#Item[0]
execute store result score @s kc_slot run data get block ~ ~ ~ Items[0].Slot
execute if score @s kc_slot matches 1 store result block ~ ~ ~ Items[0].Count short 1 run scoreboard players get @s kc_slot_fuel

scoreboard players reset @s kc_slot

scoreboard players operation @s kc_slot_fuel += 1 kc_numbers
