#######
# Compiled from data/kitcraft/functions/creative_menu.mcscript
# to .//data/kitcraft/functions/creative_menu.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tellraw @s {"text":""}
tellraw @s {"text":""}
tellraw @s [{"text":"<===== ","color":"aqua"},{"translate":"Select addon to display menu","color":"red"},{"text":" =====>","color":"aqua"}]
tellraw @s {"text":""}
function #kitcraft:creative_menu
tellraw @s {"text":""}
tellraw @s {"text":""}
