#######
# Compiled from data/kitcraft/functions/load.mcscript
# to .//data/kitcraft/functions/load.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function kitcraft:mcscript/load

scoreboard objectives add kc_burntime dummy
scoreboard objectives add kc_cooktime dummy
scoreboard objectives add kc_cooktime_set dummy
scoreboard objectives add kc_slot_in dummy
scoreboard objectives add kc_slot_out dummy
scoreboard objectives add kc_slot_fuel dummy
scoreboard objectives add kc_slot dummy
scoreboard objectives add kc_sneak minecraft.custom:minecraft.sneak_time
scoreboard objectives add kc_sat dummy
scoreboard objectives add kc_pl_sat dummy "Player Saturation"
scoreboard objectives add kc_eattime dummy
scoreboard objectives add kc_trash_timer dummy


scoreboard objectives add kc_numbers dummy
scoreboard players set 0 kc_numbers 0
scoreboard players set 1 kc_numbers 1
scoreboard players set -1 kc_numbers -1
scoreboard players set 2 kc_numbers 2
scoreboard players set -2 kc_numbers -2