#######
# Compiled from data/kitcraft/functions/main.mcscript
# to .//data/kitcraft/functions/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function kitcraft:blocks/oven/main
function kitcraft:blocks/cutting_board/main
function kitcraft:blocks/sink/main
function kitcraft:blocks/trash_can/main
function kitcraft:noplacing/detect
function kitcraft:eating/main