#######
# Compiled from data/kitcraft/functions/management.mcscript
# to .//data/kitcraft/functions/uninstall.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard objectives remove kc_burntime
scoreboard objectives remove kc_cooktime
scoreboard objectives remove kc_cooktime_set
scoreboard objectives remove kc_slot_in
scoreboard objectives remove kc_slot_out
scoreboard objectives remove kc_slot_fuel
scoreboard objectives remove kc_slot
scoreboard objectives remove kc_sneak
scoreboard objectives remove kc_sat
scoreboard objectives remove kc_pl_sat
scoreboard objectives remove kc_eattime
scoreboard objectives remove kc_req_eattime
scoreboard objectives remove kc_growth_time
scoreboard objectives remove kc_numbers
scoreboard objectives remove kc_random
scoreboard objectives remove kc_random_range

tellraw @s {"text":"Successfully uninstalled kitcraft version b1.0","color":"blue","hoverEvent":{"action":"show_text","value":":("}}
datapack disable "file/kitcraft"