#######
# Compiled from kitcraft/functions/blocks/fruit_picker.mcscript
# to .//data/kitcraft/functions/blocks/fruit_picker/craft.mcfunction
#
# Generated by Minecraft Script for 1.13
######
advancement revoke @s only kitcraft:craft_fruit_picker_utility
recipe take @s kitcraft:fruit_picker
clear @s minecraft:structure_void 1
scoreboard players set @s kc_c_menu_m 18
