#######
# Compiled from kitcraft/functions/blocks/fruit_picker.mcscript
# to .//data/kitcraft/functions/blocks/fruit_picker/destroy.mcfunction
#
# Generated by Minecraft Script for 1.13
######
kill @s[type=armor_stand]
kill @e[type=armor_stand,tag=kitcraft_fruit_picker_vis,limit=1,sort=nearest]
data merge entity @e[type=item,limit=1,sort=nearest,distance=..2,nbt={Item:{id:"minecraft:dirt",Count:1b}}] {Item:{id:"minecraft:armor_stand",Count:1b,tag:{CustomModelData:705107,kitcraft:{id:"fruit_picker_place"},display:{Name:"{\"translate\":\"Fruit Picker\",\"italic\":\"false\"}",Lore:["{\"translate\":\"Right-click to place\",\"italic\":\"false\",\"color\":\"dark_green\"}"]},EntityTag:{NoGravity:1b,Invulnerable:1b,Small:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,Tags:["kitcraft_fruit_picker","kitcraft_fruit_picker_init"]}}}}
