#######
# Compiled from kitcraft/functions/blocks/fruit_picker.mcscript
# to .//data/kitcraft/functions/blocks/fruit_picker/harvest_fruit.mcfunction
#
# Generated by Minecraft Script for 1.13
######
summon item ~ ~-1 ~ {Item:{id:"minecraft:arrow",Count:1b},Tags:["kitcraft_fruit_picker_harvested_fruit"]}
execute positioned ~ ~-1 ~ run data modify entity @e[type=minecraft:item,tag=kitcraft_fruit_picker_harvested_fruit,limit=1,sort=nearest] Item.id set from entity @s HandItems[0].id
execute positioned ~ ~-1 ~ run data modify entity @e[type=minecraft:item,tag=kitcraft_fruit_picker_harvested_fruit,limit=1,sort=nearest] Item.Count set from entity @s HandItems[0].Count
execute positioned ~ ~-1 ~ run data modify entity @e[type=minecraft:item,tag=kitcraft_fruit_picker_harvested_fruit,limit=1,sort=nearest] Item.tag set from entity @s HandItems[0].tag
replaceitem entity @s weapon.mainhand air