#######
# Compiled from kitcraft/functions/blocks/fruit_picker.mcscript
# to .//data/kitcraft/functions/blocks/fruit_picker/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function kitcraft:blocks/fruit_picker/place/detect
execute as @e[tag=kitcraft_fruit_picker] at @s unless block ~ ~ ~ minecraft:dirt run function kitcraft:blocks/fruit_picker/destroy
execute as @e[tag=kitcraft_fruit_picker] at @s run scoreboard players reset @s kc_count
execute as @e[type=armor_stand,tag=kitcraft_fruit_picker_vis] run data merge entity @s {Fire:1000s}
kill @e[type=armor_stand,tag=kitcraft_fruit_picker_detect]
