#######
# Compiled from kitcraft/functions/blocks/kitchen_counter.mcscript
# to .//data/kitcraft/functions/blocks/kitchen_counter/sink/disable.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tag @s remove kitcraft_kitchen_counter_sink
localDebug(Sink for kitchen counter deactivated)
