#######
# Compiled from kitcraft/functions/blocks/kitchen_counter.mcscript
# to .//data/kitcraft/functions/blocks/kitchen_counter/sink/empty_bucket_salmon.mcfunction
#
# Generated by Minecraft Script for 1.13
######
replaceitem block ~ ~ ~ container.9 minecraft:salmon
replaceitem block ~ ~ ~ container.18 minecraft:bucket
playsound minecraft:item.bucket.fill block @a[distance=..10] ~ ~ ~
