#######
# Compiled from kitcraft/functions/blocks/kitchen_counter.mcscript
# to .//data/kitcraft/functions/blocks/kitchen_counter/sink/empty_bowl.mcfunction
#
# Generated by Minecraft Script for 1.13
######
replaceitem block ~ ~ ~ container.9 air
replaceitem block ~ ~ ~ container.18 minecraft:bowl
playsound minecraft:item.bucket.fill block @a[distance=..10] ~ ~ ~
