#######
# Compiled from kitcraft/functions/blocks/kitchen_counter.mcscript
# to .//data/kitcraft/functions/blocks/kitchen_counter/sink/empty.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{id:"minecraft:water_bucket"}}] at @s run function kitcraft:blocks/sink/empty_item/visuals
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{id:"minecraft:water_bucket"}}] at @s run data merge entity @s {Item:{id:"minecraft:bucket"}}
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{id:"minecraft:water_bucket"}}] at @s run playsound minecraft:item.bucket.fill block @a[distance=..10] ~ ~ ~
execute if block ~ ~ ~ minecraft:barrel{Items:[{Slot:9b,id:"minecraft:water_bucket"}]} unless block ~ ~ ~ minecraft:barrel{Items:[{Slot:18b}]} run replaceitem block ~ ~ ~ container.9 air
execute if block ~ ~ ~ minecraft:barrel{Items:[{Slot:9b,id:"minecraft:water_bucket"}]} unless block ~ ~ ~ minecraft:barrel{Items:[{Slot:18b}]} run replaceitem block ~ ~ ~ container.18 minecraft:bucket
execute if block ~ ~ ~ minecraft:barrel{Items:[{Slot:9b,id:"minecraft:water_bucket"}]} unless block ~ ~ ~ minecraft:barrel{Items:[{Slot:18b}]} run playsound minecraft:item.bucket.fill block @a[distance=..10] ~ ~ ~

execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{id:"minecraft:potion"}}] at @s run function kitcraft:blocks/sink/empty_item/visuals
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{id:"minecraft:potion"}}] at @s run data remove entity @s Item.tag
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{id:"minecraft:potion"}}] at @s run data merge entity @s {Item:{id:"minecraft:glass_bottle"}}
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{id:"minecraft:potion"}}] at @s run playsound minecraft:item.bucket.fill block @a[distance=..10] ~ ~ ~
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{id:"minecraft:splash_potion"}}] at @s run function kitcraft:blocks/sink/empty_item/visuals
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{id:"minecraft:splash_potion"}}] at @s run data remove entity @s Item.tag
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{id:"minecraft:splash_potion"}}] at @s run data merge entity @s {Item:{id:"minecraft:glass_bottle"}}
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{id:"minecraft:splash_potion"}}] at @s run playsound minecraft:item.bucket.fill block @a[distance=..10] ~ ~ ~
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{id:"minecraft:milk_bucket"}}] at @s run function kitcraft:blocks/sink/empty_item/visuals
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{id:"minecraft:milk_bucket"}}] at @s run data merge entity @s {Item:{id:"minecraft:bucket"}}
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{id:"minecraft:milk_bucket"}}] at @s run playsound minecraft:item.bucket.fill block @a[distance=..10] ~ ~ ~
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{id:"minecraft:lava_bucket"}}] at @s run function kitcraft:blocks/sink/empty_item/visuals
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{id:"minecraft:lava_bucket"}}] at @s run data merge entity @s {Item:{id:"minecraft:bucket"}}
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{id:"minecraft:lava_bucket"}}] at @s run playsound minecraft:item.bucket.fill block @a[distance=..10] ~ ~ ~
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{id:"minecraft:pufferfish_bucket"}}] at @s run function kitcraft:blocks/sink/empty_item/visuals
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{id:"minecraft:pufferfish_bucket"}}] at @s run data remove entity @s Item.tag
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{id:"minecraft:pufferfish_bucket"}}] at @s run summon item ~ ~.5 ~ {Item:{id:"minecraft:pufferfish",Count:1}}
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{id:"minecraft:pufferfish_bucket"}}] at @s run data merge entity @s {Item:{id:"minecraft:bucket"}}
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{id:"minecraft:pufferfish_bucket"}}] at @s run playsound minecraft:item.bucket.fill block @a[distance=..10] ~ ~ ~
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{id:"minecraft:salmon_bucket"}}] at @s run function kitcraft:blocks/sink/empty_item/visuals
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{id:"minecraft:salmon_bucket"}}] at @s run data remove entity @s Item.tag
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{id:"minecraft:salmon_bucket"}}] at @s run summon item ~ ~.5 ~ {Item:{id:"minecraft:salmon",Count:1}}
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{id:"minecraft:salmon_bucket"}}] at @s run data merge entity @s {Item:{id:"minecraft:bucket"}}
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{id:"minecraft:salmon_bucket"}}] at @s run playsound minecraft:item.bucket.fill block @a[distance=..10] ~ ~ ~
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{id:"minecraft:cod_bucket"}}] at @s run function kitcraft:blocks/sink/empty_item/visuals
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{id:"minecraft:cod_bucket"}}] at @s run data remove entity @s Item.tag
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{id:"minecraft:cod_bucket"}}] at @s run summon item ~ ~.5 ~ {Item:{id:"minecraft:cod",Count:1}}
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{id:"minecraft:cod_bucket"}}] at @s run data merge entity @s {Item:{id:"minecraft:bucket"}}
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{id:"minecraft:cod_bucket"}}] at @s run playsound minecraft:item.bucket.fill block @a[distance=..10] ~ ~ ~
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{id:"minecraft:tropical_fish_bucket"}}] at @s run function kitcraft:blocks/sink/empty_item/visuals
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{id:"minecraft:tropical_fish_bucket"}}] at @s run data remove entity @s Item.tag
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{id:"minecraft:tropical_fish_bucket"}}] at @s run summon item ~ ~.5 ~ {Item:{id:"minecraft:tropical_fish",Count:1}}
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{id:"minecraft:tropical_fish_bucket"}}] at @s run data merge entity @s {Item:{id:"minecraft:bucket"}}
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{id:"minecraft:tropical_fish_bucket"}}] at @s run playsound minecraft:item.bucket.fill block @a[distance=..10] ~ ~ ~
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{id:"minecraft:mushroom_stew"}}] at @s run function kitcraft:blocks/sink/empty_item/visuals
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{id:"minecraft:mushroom_stew"}}] at @s run data merge entity @s {Item:{id:"minecraft:bowl"}}
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{id:"minecraft:mushroom_stew"}}] at @s run playsound minecraft:item.bucket.fill block @a[distance=..10] ~ ~ ~
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{id:"minecraft:rabbit_stew"}}] at @s run function kitcraft:blocks/sink/empty_item/visuals
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{id:"minecraft:rabbit_stew"}}] at @s run data merge entity @s {Item:{id:"minecraft:bowl"}}
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{id:"minecraft:rabbit_stew"}}] at @s run playsound minecraft:item.bucket.fill block @a[distance=..10] ~ ~ ~
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{id:"minecraft:beetroot_soup"}}] at @s run function kitcraft:blocks/sink/empty_item/visuals
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{id:"minecraft:beetroot_soup"}}] at @s run data merge entity @s {Item:{id:"minecraft:bowl"}}
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{id:"minecraft:beetroot_soup"}}] at @s run playsound minecraft:item.bucket.fill block @a[distance=..10] ~ ~ ~
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{tag:{kitcraft:{containerItem:"bucket"}}}}] at @s run function kitcraft:blocks/sink/empty_item/visuals
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{tag:{kitcraft:{containerItem:"bucket"}}}}] at @s run data remove entity @s Item.tag
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{tag:{kitcraft:{containerItem:"bucket"}}}}] at @s run data merge entity @s {Item:{id:"minecraft:bucket"}}
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{tag:{kitcraft:{containerItem:"bucket"}}}}] at @s run playsound minecraft:item.bucket.fill block @a[distance=..10] ~ ~ ~
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{tag:{kitcraft:{containerItem:"bottle"}}}}] at @s run function kitcraft:blocks/sink/empty_item/visuals
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{tag:{kitcraft:{containerItem:"bottle"}}}}] at @s run data remove entity @s Item.tag
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{tag:{kitcraft:{containerItem:"bottle"}}}}] at @s run data merge entity @s {Item:{id:"minecraft:glass_bottle"}}
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{tag:{kitcraft:{containerItem:"bottle"}}}}] at @s run playsound minecraft:item.bucket.fill block @a[distance=..10] ~ ~ ~
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{tag:{kitcraft:{containerItem:"bowl"}}}}] at @s run function kitcraft:blocks/sink/empty_item/visuals
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{tag:{kitcraft:{containerItem:"bowl"}}}}] at @s run data remove entity @s Item.tag
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{tag:{kitcraft:{containerItem:"bowl"}}}}] at @s run data merge entity @s {Item:{id:"minecraft:bowl"}}
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{tag:{kitcraft:{containerItem:"bowl"}}}}] at @s run playsound minecraft:item.bucket.fill block @a[distance=..10] ~ ~ ~
