#######
# Compiled from kitcraft/functions/blocks/kitchen_counter.mcscript
# to .//data/kitcraft/functions/blocks/kitchen_counter/sink/enable.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tag @s add kitcraft_kitchen_counter_sink
replaceitem block ~ ~ ~ container.9 air
replaceitem block ~ ~ ~ container.18 air
localDebug(Sink for kitchen counter activated)
