#######
# Compiled from kitcraft/functions/blocks/kitchen_counter.mcscript
# to .//data/kitcraft/functions/blocks/kitchen_counter/sink/enable.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tag @s add kitcraft_kitchen_counter_sink
replaceitem block ~ ~ ~ container.9 air
replaceitem block ~ ~ ~ container.18 air
tellraw @a[tag=kitcraft_receive_debug,distance=..15] [{"text":"kitcraft debug => ","color":"aqua","hoverEvent":{"action":"show_text","value":"Click to stop receiving this messages"},"clickEvent":{"action":"run_command","value":"/tag @s remove kitcraft_receive_debug"}},{"text":"Sink for kitchen counter activated","color":"reset","bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"hoverEvent":{"action":"show_text","value":"-no info-"}}]
