#######
# Compiled from kitcraft/functions/blocks/kitchen_counter.mcscript
# to .//data/kitcraft/functions/blocks/kitchen_counter/sink/fill_bottle.mcfunction
#
# Generated by Minecraft Script for 1.13
######
replaceitem block ~ ~ ~ container.18 minecraft:potion{Potion:"minecraft:water"}
execute store result score @s kc_temp run data get block ~ ~ ~ Items[{Slot:9b}].Count
scoreboard players remove @s kc_temp 1
execute store result block ~ ~ ~ Items[{Slot:9b}].Count byte 1 run scoreboard players get @s kc_temp
scoreboard players reset @s kc_temp
playsound minecraft:item.bucket.fill block @a[distance=..10] ~ ~ ~
