#######
# Compiled from kitcraft/functions/blocks/kitchen_counter.mcscript
# to .//data/kitcraft/functions/blocks/kitchen_counter/sink/function_detect.mcfunction
#
# Generated by Minecraft Script for 1.13
######
#fill
execute if block ~ ~ ~ minecraft:barrel{Items:[{Slot:9b,id:"minecraft:bucket"}]} unless block ~ ~ ~ minecraft:barrel{Items:[{Slot:18b}]} run function kitcraft:blocks/kitchen_counter/sink/fill_bucket

execute if block ~ ~ ~ minecraft:barrel{Items:[{Slot:9b,id:"minecraft:glass_bottle"}]} unless block ~ ~ ~ minecraft:barrel{Items:[{Slot:18b}]} run function kitcraft:blocks/kitchen_counter/sink/fill_bottle


#empty
execute if data block ~ ~ ~ Items[{Slot:9b}].tag.kitcraft.containerItem.id unless block ~ ~ ~ minecraft:barrel{Items:[{Slot:18b}]} run function kitcraft:blocks/kitchen_counter/sink/empty_custom

execute if block ~ ~ ~ minecraft:barrel{Items:[{Slot:9b,tag:{kitcraft:{containerItem:"bucket"}}}]} unless block ~ ~ ~ minecraft:barrel{Items:[{Slot:18b}]} run function kitcraft:blocks/kitchen_counter/sink/empty_bucket

execute if block ~ ~ ~ minecraft:barrel{Items:[{Slot:9b,tag:{kitcraft:{containerItem:"bottle"}}}]} unless block ~ ~ ~ minecraft:barrel{Items:[{Slot:18b}]} run function kitcraft:blocks/kitchen_counter/sink/empty_bottle

execute if block ~ ~ ~ minecraft:barrel{Items:[{Slot:9b,tag:{kitcraft:{containerItem:"bowl"}}}]} unless block ~ ~ ~ minecraft:barrel{Items:[{Slot:18b}]} run function kitcraft:blocks/kitchen_counter/sink/empty_bowl

execute if block ~ ~ ~ minecraft:barrel{Items:[{Slot:9b,id:"minecraft:water_bucket"}]} unless block ~ ~ ~ minecraft:barrel{Items:[{Slot:18b}]} run function kitcraft:blocks/kitchen_counter/sink/empty_bucket

execute if block ~ ~ ~ minecraft:barrel{Items:[{Slot:9b,id:"minecraft:milk_bucket"}]} unless block ~ ~ ~ minecraft:barrel{Items:[{Slot:18b}]} run function kitcraft:blocks/kitchen_counter/sink/empty_bucket

execute if block ~ ~ ~ minecraft:barrel{Items:[{Slot:9b,id:"minecraft:lava_bucket"}]} unless block ~ ~ ~ minecraft:barrel{Items:[{Slot:18b}]} run function kitcraft:blocks/kitchen_counter/sink/empty_bucket

execute if block ~ ~ ~ minecraft:barrel{Items:[{Slot:9b,id:"minecraft:potion"}]} unless block ~ ~ ~ minecraft:barrel{Items:[{Slot:18b}]} run function kitcraft:blocks/kitchen_counter/sink/empty_bottle

execute if block ~ ~ ~ minecraft:barrel{Items:[{Slot:9b,id:"minecraft:splash_potion"}]} unless block ~ ~ ~ minecraft:barrel{Items:[{Slot:18b}]} run function kitcraft:blocks/kitchen_counter/sink/empty_bottle

execute if block ~ ~ ~ minecraft:barrel{Items:[{Slot:9b,id:"minecraft:pufferfish_bucket"}]} unless block ~ ~ ~ minecraft:barrel{Items:[{Slot:18b}]} run function kitcraft:blocks/kitchen_counter/sink/empty_bucket_pufferfish

execute if block ~ ~ ~ minecraft:barrel{Items:[{Slot:9b,id:"minecraft:salmon_bucket"}]} unless block ~ ~ ~ minecraft:barrel{Items:[{Slot:18b}]} run function kitcraft:blocks/kitchen_counter/sink/empty_bucket_salmon

execute if block ~ ~ ~ minecraft:barrel{Items:[{Slot:9b,id:"minecraft:cod_bucket"}]} unless block ~ ~ ~ minecraft:barrel{Items:[{Slot:18b}]} run function kitcraft:blocks/kitchen_counter/sink/empty_bucket_cod

execute if block ~ ~ ~ minecraft:barrel{Items:[{Slot:9b,id:"minecraft:tropical_fish_bucket"}]} unless block ~ ~ ~ minecraft:barrel{Items:[{Slot:18b}]} run function kitcraft:blocks/kitchen_counter/sink/empty_bucket_tropical_fish

execute if block ~ ~ ~ minecraft:barrel{Items:[{Slot:9b,id:"minecraft:mushroom_stew"}]} unless block ~ ~ ~ minecraft:barrel{Items:[{Slot:18b}]} run function kitcraft:blocks/kitchen_counter/sink/empty_bowl

execute if block ~ ~ ~ minecraft:barrel{Items:[{Slot:9b,id:"minecraft:rabbit_stew"}]} unless block ~ ~ ~ minecraft:barrel{Items:[{Slot:18b}]} run function kitcraft:blocks/kitchen_counter/sink/empty_bowl

execute if block ~ ~ ~ minecraft:barrel{Items:[{Slot:9b,id:"minecraft:beetroot_soup"}]} unless block ~ ~ ~ minecraft:barrel{Items:[{Slot:18b}]} run function kitcraft:blocks/kitchen_counter/sink/empty_bowl

