#######
# Compiled from data/kitcraft/functions/load.mcscript
# to .//data/kitcraft/functions/mcscript/load.mcfunction
#
# Generated by Minecraft Script for 1.13
######

# Extended from data/kitcraft/functions/random.mcscript
# to data/kitcraft/functions/mcscript/load.mcfunction
# please do not touch this file!
# it is used by the compiler!
scoreboard objectives add kc_temp dummy
