#######
# Compiled from kitcraft/functions/blocks/sink.mcscript
# to .//data/kitcraft/functions/blocks/sink/place/place.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tag @s remove kitcraft_sink_init
setblock ~ ~ ~ minecraft:cauldron[level=3]
