#######
# Compiled from kitcraft/functions/blocks/cutting_board.mcscript
# to .//data/kitcraft/functions/blocks/cutting_board/craft.mcfunction
#
# Generated by Minecraft Script for 1.13
######
advancement revoke @s only kitcraft:craft_cutting_board_utility
recipe take @s kitcraft:cutting_board
clear @s minecraft:structure_void 1
function kitcraft:give/blocks/cutting_board
