#######
# Compiled from kitcraft/functions/blocks/cutting_board.mcscript
# to .//data/kitcraft/functions/blocks/cutting_board/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @e[tag=kitcraft_cutting_board_vis_init] at @s store result entity @s Rotation[0] float 1 run data get entity @e[tag=kitcraft_cutting_board,limit=1,sort=nearest] Rotation[0]
function kitcraft:blocks/cutting_board/place/detect
function kitcraft:blocks/cutting_board/destroy/detect
execute as @e[type=armor_stand,tag=kitcraft_cutting_board] at @s run function #kitcraft:cutting_board_recipes
execute as @e[tag=kitcraft_cutting_board_vis] run data merge entity @s {Fire:1000}
