#######
# Compiled from kitcraft/functions/blocks/cutting_board.mcscript
# to .//data/kitcraft/functions/blocks/cutting_board/recipes.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function kitcraft:blocks/cutting_board/recipes/potato_slice
function kitcraft:blocks/cutting_board/recipes/potato_sticks
