#######
# Compiled from kitcraft/functions/blocks/kitchen_counter.mcscript
# to .//data/kitcraft/functions/blocks/kitchen_counter/recipes/lemon_soda/1.mcfunction
#
# Generated by Minecraft Script for 1.13
######
replaceitem block ~ ~ ~ container.15 minecraft:dead_bubble_coral{display:{Name:"{\"translate\":\"Lemon Soda\",\"italic\":false}",Lore:["{\"translate\":\"Press shift while holding to eat\",\"color\":\"dark_green\",\"italic\":false}"]},CustomModelData:7050009,kitcraft:{id:"lemon_soda",NoPlacing:1b,containerItem:"bottle",Eatable:2,sat:5,particle:"water",Drink:1,EatNoHunger:1}} 2
tag @s add kitcraft_kitchen_counter_crafted
tag @s add kitcraft_kitchen_counter_crafted_lemon_soda
