#######
# Compiled from data/kitcraft/functions/eating.mcscript
# to .//data/kitcraft/functions/eating/add_eattime.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute unless score @s kc_eattime > @s kc_req_eattime run scoreboard players add @s kc_eattime 1
execute if score @s kc_eattime > @s kc_req_eattime run scoreboard players reset @s kc_eattime
