#######
# Compiled from data/kitcraft/functions/eating.mcscript
# to .//data/kitcraft/functions/eating/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######

execute as @a at @s if entity @s[nbt={SelectedItem:{tag:{kitcraft:{Eatable:1}}}}] run function kitcraft:eating/set_values
execute as @a at @s if entity @s[nbt={SelectedItem:{tag:{kitcraft:{Eatable:2}}}}] run function kitcraft:eating/set_values
execute as @a at @s unless entity @s[nbt={SelectedItem:{tag:{kitcraft:{Eatable:1}}}}] unless entity @s[nbt={SelectedItem:{tag:{kitcraft:{Eatable:2}}}}] run scoreboard players reset @s kc_pl_sat
execute as @a at @s unless entity @s[nbt={SelectedItem:{tag:{kitcraft:{Eatable:1}}}}] unless entity @s[nbt={SelectedItem:{tag:{kitcraft:{Eatable:2}}}}] run scoreboard players reset @s kc_req_eattime
execute as @a at @s if entity @s[gamemode=!spectator,scores={kc_sneak=1..},nbt={OnGround:1b,SelectedItem:{tag:{kitcraft:{Eatable:1}}}}] if entity @s[nbt={SelectedItem:{tag:{kitcraft:{EatNoHunger:1}}}}] run function kitcraft:eating/add_eattime
execute as @a at @s if entity @s[gamemode=!spectator,scores={kc_sneak=1..},nbt={OnGround:1b,SelectedItem:{tag:{kitcraft:{Eatable:2}}}}] if entity @s[nbt={SelectedItem:{tag:{kitcraft:{EatNoHunger:1}}}}] run function kitcraft:eating/add_eattime
execute as @a at @s if entity @s[gamemode=!spectator,scores={kc_sneak=1..},nbt={OnGround:1b,SelectedItem:{tag:{kitcraft:{Eatable:1}}}}] unless entity @s[nbt={SelectedItem:{tag:{kitcraft:{EatNoHunger:1}}}}] if entity @s[gamemode=!creative,scores={kc_pl_sat=..19}] run function kitcraft:eating/add_eattime
execute as @a at @s if entity @s[gamemode=!spectator,scores={kc_sneak=1..},nbt={OnGround:1b,SelectedItem:{tag:{kitcraft:{Eatable:2}}}}] unless entity @s[nbt={SelectedItem:{tag:{kitcraft:{EatNoHunger:1}}}}] if entity @s[gamemode=!creative,scores={kc_pl_sat=..19}] run function kitcraft:eating/add_eattime

execute as @a[scores={kc_eattime=1..}] at @s if entity @s[nbt={SelectedItem:{tag:{kitcraft:{EatNoHunger:1}}}}] run function #kitcraft:eat_particles
execute as @a[scores={kc_eattime=1..}] at @s if entity @s[nbt={SelectedItem:{tag:{kitcraft:{EatNoHunger:1}}}}] run function kitcraft:eating/sounds
execute as @a[scores={kc_eattime=1..}] at @s unless entity @s[nbt={SelectedItem:{tag:{kitcraft:{EatNoHunger:1}}}}] if entity @s[scores={kc_pl_sat=..19}] run function #kitcraft:eat_particles
execute as @a[scores={kc_eattime=1..}] at @s unless entity @s[nbt={SelectedItem:{tag:{kitcraft:{EatNoHunger:1}}}}] if entity @s[scores={kc_pl_sat=..19}] run function kitcraft:eating/sounds

execute as @a at @s if entity @s[nbt={SelectedItem:{tag:{kitcraft:{EatNoHunger:1}}}}] run function #kitcraft:eat_food
execute as @a at @s if entity @s[nbt={SelectedItem:{tag:{kitcraft:{EatNoHunger:1}}}}] run function kitcraft:eating/simple_food
execute as @a at @s unless entity @s[nbt={SelectedItem:{tag:{kitcraft:{EatNoHunger:1}}}}] if entity @s[scores={kc_pl_sat=..19}] run function #kitcraft:eat_food
execute as @a at @s unless entity @s[nbt={SelectedItem:{tag:{kitcraft:{EatNoHunger:1}}}}] if entity @s[scores={kc_pl_sat=..19}] run function kitcraft:eating/simple_food

execute as @a at @s if score @s kc_eattime >= @s kc_req_eattime run function kitcraft:eating/saturate

execute as @a[scores={kc_eattime=1..}] at @s unless entity @s[nbt={SelectedItem:{tag:{kitcraft:{Eatable:1}}}}] unless entity @s[nbt={SelectedItem:{tag:{kitcraft:{Eatable:2}}}}] run scoreboard players reset @s kc_eattime
execute as @a[scores={kc_eattime=1..}] at @s unless entity @s[scores={kc_sneak=1..}] run scoreboard players reset @s kc_eattime


scoreboard players reset @a kc_sneak
