#######
# Compiled from data/kitcraft/functions/eating.mcscript
# to .//data/kitcraft/functions/eating/particle.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"white"}}}}] positioned ~ ~1.2 ~ run particle minecraft:block white_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"orange"}}}}] positioned ~ ~1.2 ~ run particle minecraft:block orange_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"magenta"}}}}] positioned ~ ~1.2 ~ run particle minecraft:block magenta_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"light_blue"}}}}] positioned ~ ~1.2 ~ run particle minecraft:block light_blue_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"yellow"}}}}] positioned ~ ~1.2 ~ run particle minecraft:block yellow_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"lime"}}}}] positioned ~ ~1.2 ~ run particle minecraft:block lime_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"pink"}}}}] positioned ~ ~1.2 ~ run particle minecraft:block pink_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"gray"}}}}] positioned ~ ~1.2 ~ run particle minecraft:block gray_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"light_gray"}}}}] positioned ~ ~1.2 ~ run particle minecraft:block light_gray_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"cyan"}}}}] positioned ~ ~1.2 ~ run particle minecraft:block cyan_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"purple"}}}}] positioned ~ ~1.2 ~ run particle minecraft:block purple_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"blue"}}}}] positioned ~ ~1.2 ~ run particle minecraft:block blue_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"brown"}}}}] positioned ~ ~1.2 ~ run particle minecraft:block brown_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"green"}}}}] positioned ~ ~1.2 ~ run particle minecraft:block green_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"red"}}}}] positioned ~ ~1.2 ~ run particle minecraft:block red_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"black"}}}}] positioned ~ ~1.2 ~ run particle minecraft:block black_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
