#######
# Compiled from data/kitcraft/functions/eating.mcscript
# to .//data/kitcraft/functions/eating/particle.mcfunction
#
# Generated by Minecraft Script for 1.13
######
#Basic Colors
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"white"}}}}] positioned ~ ~1.2 ~ run particle minecraft:block white_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"orange"}}}}] positioned ~ ~1.2 ~ run particle minecraft:block orange_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"magenta"}}}}] positioned ~ ~1.2 ~ run particle minecraft:block magenta_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"light_blue"}}}}] positioned ~ ~1.2 ~ run particle minecraft:block light_blue_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"yellow"}}}}] positioned ~ ~1.2 ~ run particle minecraft:block yellow_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"lime"}}}}] positioned ~ ~1.2 ~ run particle minecraft:block lime_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"pink"}}}}] positioned ~ ~1.2 ~ run particle minecraft:block pink_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"gray"}}}}] positioned ~ ~1.2 ~ run particle minecraft:block gray_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"light_gray"}}}}] positioned ~ ~1.2 ~ run particle minecraft:block light_gray_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"cyan"}}}}] positioned ~ ~1.2 ~ run particle minecraft:block cyan_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"purple"}}}}] positioned ~ ~1.2 ~ run particle minecraft:block purple_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"blue"}}}}] positioned ~ ~1.2 ~ run particle minecraft:block blue_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"brown"}}}}] positioned ~ ~1.2 ~ run particle minecraft:block brown_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"green"}}}}] positioned ~ ~1.2 ~ run particle minecraft:block green_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"red"}}}}] positioned ~ ~1.2 ~ run particle minecraft:block red_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"black"}}}}] positioned ~ ~1.2 ~ run particle minecraft:block black_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s



#Effects
#Rainbow
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"rainbow"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 1 run particle minecraft:block red_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"rainbow"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 8 run particle minecraft:block red_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"rainbow"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 15 run particle minecraft:block red_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"rainbow"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 22 run particle minecraft:block red_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"rainbow"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 29 run particle minecraft:block red_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"rainbow"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 36 run particle minecraft:block red_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"rainbow"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 2 run particle minecraft:block orange_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"rainbow"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 9 run particle minecraft:block orange_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"rainbow"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 16 run particle minecraft:block orange_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"rainbow"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 23 run particle minecraft:block orange_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"rainbow"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 30 run particle minecraft:block orange_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"rainbow"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 37 run particle minecraft:block orange_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"rainbow"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 3 run particle minecraft:block yellow_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"rainbow"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 10 run particle minecraft:block yellow_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"rainbow"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 17 run particle minecraft:block yellow_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"rainbow"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 24 run particle minecraft:block yellow_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"rainbow"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 31 run particle minecraft:block yellow_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"rainbow"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 38 run particle minecraft:block yellow_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"rainbow"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 4 run particle minecraft:block lime_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"rainbow"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 11 run particle minecraft:block lime_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"rainbow"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 18 run particle minecraft:block lime_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"rainbow"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 25 run particle minecraft:block lime_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"rainbow"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 32 run particle minecraft:block lime_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"rainbow"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 39 run particle minecraft:block lime_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"rainbow"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 5 run particle minecraft:block light_blue_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"rainbow"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 12 run particle minecraft:block light_blue_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"rainbow"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 19 run particle minecraft:block light_blue_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"rainbow"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 26 run particle minecraft:block light_blue_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"rainbow"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 33 run particle minecraft:block light_blue_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"rainbow"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 40 run particle minecraft:block light_blue_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"rainbow"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 6 run particle minecraft:block blue_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"rainbow"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 13 run particle minecraft:block blue_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"rainbow"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 20 run particle minecraft:block blue_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"rainbow"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 27 run particle minecraft:block blue_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"rainbow"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 34 run particle minecraft:block blue_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"rainbow"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 41 run particle minecraft:block blue_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"rainbow"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 7 run particle minecraft:block magenta_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"rainbow"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 14 run particle minecraft:block magenta_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"rainbow"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 21 run particle minecraft:block magenta_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"rainbow"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 28 run particle minecraft:block magenta_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"rainbow"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 35 run particle minecraft:block magenta_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"rainbow"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 42 run particle minecraft:block magenta_concrete ^ ^ ^0.4 0.4 0.4 0.4 1 0 force @s

#Ender
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"ender"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 1..3 run particle minecraft:block minecraft:purple_concrete ^ ^ ^.4 .4 .4 .4 1 0
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"ender"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 7..9 run particle minecraft:block minecraft:purple_concrete ^ ^ ^.4 .4 .4 .4 1 0
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"ender"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 13..15 run particle minecraft:block minecraft:purple_concrete ^ ^ ^.4 .4 .4 .4 1 0
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"ender"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 19..21 run particle minecraft:block minecraft:purple_concrete ^ ^ ^.4 .4 .4 .4 1 0
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"ender"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 25..27 run particle minecraft:block minecraft:purple_concrete ^ ^ ^.4 .4 .4 .4 1 0
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"ender"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 30..32 run particle minecraft:block minecraft:purple_concrete ^ ^ ^.4 .4 .4 .4 1 0
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"ender"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 36..38 run particle minecraft:block minecraft:purple_concrete ^ ^ ^.4 .4 .4 .4 1 0
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"ender"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 4..5 run particle minecraft:block minecraft:magenta_concrete ^ ^ ^.4 .4 .4 .4 1 0
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"ender"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 10..11 run particle minecraft:block minecraft:magenta_concrete ^ ^ ^.4 .4 .4 .4 1 0
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"ender"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 16..17 run particle minecraft:block minecraft:magenta_concrete ^ ^ ^.4 .4 .4 .4 1 0
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"ender"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 22..23 run particle minecraft:block minecraft:magenta_concrete ^ ^ ^.4 .4 .4 .4 1 0
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"ender"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 27..28 run particle minecraft:block minecraft:magenta_concrete ^ ^ ^.4 .4 .4 .4 1 0
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"ender"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 33..34 run particle minecraft:block minecraft:magenta_concrete ^ ^ ^.4 .4 .4 .4 1 0
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"ender"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 39..40 run particle minecraft:block minecraft:magenta_concrete ^ ^ ^.4 .4 .4 .4 1 0
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"ender"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 6 run particle minecraft:block minecraft:gray_concrete ^ ^ ^.4 .4 .4 .4 1 0
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"ender"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 12 run particle minecraft:block minecraft:gray_concrete ^ ^ ^.4 .4 .4 .4 1 0
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"ender"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 18 run particle minecraft:block minecraft:gray_concrete ^ ^ ^.4 .4 .4 .4 1 0
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"ender"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 24 run particle minecraft:block minecraft:gray_concrete ^ ^ ^.4 .4 .4 .4 1 0
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"ender"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 29 run particle minecraft:block minecraft:gray_concrete ^ ^ ^.4 .4 .4 .4 1 0
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"ender"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 35 run particle minecraft:block minecraft:gray_concrete ^ ^ ^.4 .4 .4 .4 1 0
execute at @s[nbt={SelectedItem:{tag:{kitcraft:{particle:"ender"}}}}] positioned ~ ~1.2 ~ if score @s kc_eattime matches 41 run particle minecraft:block minecraft:gray_concrete ^ ^ ^.4 .4 .4 .4 1 0
