#######
# Compiled from data/kitcraft/functions/eating.mcscript
# to .//data/kitcraft/functions/eating/saturate.mcfunction
#
# Generated by Minecraft Script for 1.13
######
effect give @s[scores={kc_sat=1}] saturation 1 0 false
effect give @s[scores={kc_sat=2}] saturation 1 1 false
effect give @s[scores={kc_sat=3}] saturation 1 2 false
effect give @s[scores={kc_sat=4}] saturation 1 3 false
effect give @s[scores={kc_sat=5}] saturation 1 4 false
effect give @s[scores={kc_sat=6}] saturation 1 5 false
effect give @s[scores={kc_sat=7}] saturation 1 6 false
effect give @s[scores={kc_sat=8}] saturation 1 7 false
effect give @s[scores={kc_sat=9}] saturation 1 8 false
effect give @s[scores={kc_sat=10}] saturation 1 9 false
effect give @s[scores={kc_sat=11}] saturation 1 10 false
effect give @s[scores={kc_sat=12}] saturation 1 11 false
effect give @s[scores={kc_sat=13}] saturation 1 12 false
effect give @s[scores={kc_sat=14}] saturation 1 13 false
effect give @s[scores={kc_sat=15}] saturation 1 14 false
effect give @s[scores={kc_sat=16}] saturation 1 15 false
effect give @s[scores={kc_sat=17}] saturation 1 16 false
effect give @s[scores={kc_sat=18}] saturation 1 17 false
effect give @s[scores={kc_sat=19}] saturation 1 18 false
effect give @s[scores={kc_sat=20..}] saturation 1 19 false
