#######
# Compiled from data/kitcraft/functions/eating.mcscript
# to .//data/kitcraft/functions/eating/set_values.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute store result score @s kc_pl_sat run data get entity @s foodLevel
execute store result score @s kc_sat run data get entity @s SelectedItem.tag.kitcraft.sat
execute store result score @s kc_req_eattime run data get entity @s SelectedItem.tag.kitcraft.eattime
execute unless score @s kc_req_eattime matches 1.. run scoreboard players set @s kc_req_eattime 40

execute unless score @s kc_req_eattime matches 1 run scoreboard players remove @s kc_req_eattime 1

