#######
# Compiled from data/kitcraft/functions/eating.mcscript
# to .//data/kitcraft/functions/eating/set_values.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute store result score @s kc_sat run data get entity @s SelectedItem.tag.kitcraft.sat
