#######
# Compiled from data/kitcraft/functions/eating.mcscript
# to .//data/kitcraft/functions/eating/simple_food.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @a[nbt={SelectedItem:{id:"minecraft:dead_bubble_coral",tag:{kitcraft:{Eatable:1}}}}] at @s if score @s kc_eattime = @s kc_req_eattime run function kitcraft:eating/simple_food_consume
