#######
# Compiled from data/kitcraft/functions/eating.mcscript
# to .//data/kitcraft/functions/eating/sounds.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @a at @s if entity @s[scores={kc_eattime=5}] run playsound minecraft:entity.generic.eat player @a[distance=..5]
execute as @a at @s if entity @s[scores={kc_eattime=10}] run playsound minecraft:entity.generic.eat player @a[distance=..5]
execute as @a at @s if entity @s[scores={kc_eattime=15}] run playsound minecraft:entity.generic.eat player @a[distance=..5]
execute as @a at @s if entity @s[scores={kc_eattime=25}] run playsound minecraft:entity.generic.eat player @a[distance=..5]
execute as @a at @s if entity @s[scores={kc_eattime=30}] run playsound minecraft:entity.generic.eat player @a[distance=..5]
execute as @a at @s if entity @s[scores={kc_eattime=35}] run playsound minecraft:entity.generic.eat player @a[distance=..5]
execute as @a at @s unless entity @s[scores={kc_eattime=5}] if entity @s[scores={kc_eattime=39..}] run playsound minecraft:entity.player.burp player @a[distance=..5]
execute as @a at @s unless entity @s[scores={kc_eattime=10}] if entity @s[scores={kc_eattime=39..}] run playsound minecraft:entity.player.burp player @a[distance=..5]
execute as @a at @s unless entity @s[scores={kc_eattime=15}] if entity @s[scores={kc_eattime=39..}] run playsound minecraft:entity.player.burp player @a[distance=..5]
execute as @a at @s unless entity @s[scores={kc_eattime=25}] if entity @s[scores={kc_eattime=39..}] run playsound minecraft:entity.player.burp player @a[distance=..5]
execute as @a at @s unless entity @s[scores={kc_eattime=30}] if entity @s[scores={kc_eattime=39..}] run playsound minecraft:entity.player.burp player @a[distance=..5]
execute as @a at @s unless entity @s[scores={kc_eattime=35}] if entity @s[scores={kc_eattime=39..}] run playsound minecraft:entity.player.burp player @a[distance=..5]
