#######
# Compiled from kitcraft/functions/blocks/kitchen_counter.mcscript
# to .//data/kitcraft/functions/blocks/kitchen_counter/recipes/sweet_dough/2.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function kitcraft:blocks/kitchen_counter/crafted
replaceitem block ~ ~ ~ container.11 minecraft:bucket
tag @s remove kitcraft_kitchen_counter_crafted
tag @s remove kitcraft_kitchen_counter_crafted_sweet_dough
