#######
# Compiled from kitcraft/functions/blocks/kitchen_counter.mcscript
# to .//data/kitcraft/functions/blocks/kitchen_counter/recipes/sweet_dough/3.mcfunction
#
# Generated by Minecraft Script for 1.13
######
replaceitem block ~ ~ ~ container.15 minecraft:air
tag @s remove kitcraft_kitchen_counter_crafted
tag @s remove kitcraft_kitchen_counter_crafted_sweet_dough
