#######
# Compiled from kitcraft/functions/blocks/oven.mcscript
# to .//data/kitcraft/functions/blocks/oven/place/place_west.mcfunction
#
# Generated by Minecraft Script for 1.13
######
setblock ~ ~ ~ minecraft:furnace[facing=west]{CustomName:"{\"translate\":\"Oven\",\"italic\":\"false\"}"}
tag @s remove kitcraft_oven_init
