#######
# Compiled from kitcraft/functions/blocks/oven.mcscript
# to .//data/kitcraft/functions/blocks/oven/place/place_east.mcfunction
#
# Generated by Minecraft Script for 1.13
######
setblock ~ ~ ~ minecraft:furnace[facing=east]{CustomName:"{\"text\":\"Oven\",\"italic\":\"false\"}"}
tag @s remove kitcraft_oven_init
