#######
# Compiled from data/kitcraft/functions/noplacing.mcscript
# to .//data/kitcraft/functions/noplacing/detect.mcfunction
#
# Generated by Minecraft Script for 1.13
######
#noplace
execute as @a[tag=!kitcraft_noplacing,gamemode=survival,nbt={SelectedItem:{tag:{kitcraft:{NoPlacing:1}}}}] run function kitcraft:noplacing/noplacing

#place
execute as @a[tag=kitcraft_noplacing,gamemode=adventure] unless entity @s[nbt={SelectedItem:{tag:{kitcraft:{NoPlacing:1}}}}] run function kitcraft:noplacing/placing
execute as @a[tag=kitcraft_noplacing] unless entity @s[nbt={SelectedItem:{tag:{kitcraft:{NoPlacing:1}}}}] run tag @s remove kitcraft_noplacing

tag @a[tag=kitcraft_noplacing,gamemode=creative] remove kitcraft_noplace
gamemode adventure @a[gamemode=survival,tag=kitcraft_noplacing]
