#######
# Compiled from data/kitcraft/functions/noplacing.mcscript
# to .//data/kitcraft/functions/noplacing/noplacing.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tag @s add kitcraft_noplacing
gamemode adventure
