#######
# Compiled from data/kitcraft/functions/noplacing.mcscript
# to .//data/kitcraft/functions/noplacing/placing.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tag @s remove kitcraft_noplacing
gamemode survival