#######
# Compiled from kitcraft/functions/blocks/oven.mcscript
# to .//data/kitcraft/functions/blocks/oven/recipes/cookie.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if block ~ ~ ~ minecraft:furnace{Items:[{Slot:0b,id:"minecraft:dead_bubble_coral",tag:{kitcraft:{id:"cookie_dough"}}}]} if entity @s[scores={kc_cooktime=198}] unless block ~ ~ ~ minecraft:furnace{Items:[{Slot:2b}]} run replaceitem block ~ ~ ~ container.2 minecraft:cookie{}
execute if block ~ ~ ~ minecraft:furnace{Items:[{Slot:0b,id:"minecraft:dead_bubble_coral",tag:{kitcraft:{id:"cookie_dough"}}}]} if entity @s[scores={kc_cooktime=198}] if block ~ ~ ~ minecraft:furnace{Items:[{Slot:2b,id:"minecraft:cookie"}]} run replaceitem block ~ ~ ~ container.2 minecraft:cookie{}
execute if block ~ ~ ~ minecraft:furnace{Items:[{Slot:0b,id:"minecraft:dead_bubble_coral",tag:{kitcraft:{id:"cookie_dough"}}}]} if entity @s[scores={kc_cooktime=198}] unless block ~ ~ ~ minecraft:furnace{Items:[{Slot:2b}]} run function kitcraft:blocks/oven/cooking/count
execute if block ~ ~ ~ minecraft:furnace{Items:[{Slot:0b,id:"minecraft:dead_bubble_coral",tag:{kitcraft:{id:"cookie_dough"}}}]} if entity @s[scores={kc_cooktime=198}] if block ~ ~ ~ minecraft:furnace{Items:[{Slot:2b,id:"minecraft:cookie"}]} run function kitcraft:blocks/oven/cooking/count
