#######
# Compiled from kitcraft/functions/blocks/oven.mcscript
# to .//data/kitcraft/functions/blocks/oven/recipes/fries.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if block ~ ~ ~ minecraft:furnace{Items:[{Slot:0b,tag:{kitcraft:{id:"potato_sticks"}}}]} if entity @s[scores={kc_cooktime=198}] unless block ~ ~ ~ minecraft:furnace{Items:[{Slot:2b}]} run replaceitem block ~ ~ ~ container.2 minecraft:dead_bubble_coral{kitcraft:{Eatable:1,sat:6,particle:"yellow",id:"fries",NoPlacing:1},CustomModelData:7050003,display:{Name:"{\"translate\":\"Fries\",\"italic\":\"false\"}",Lore:["{\"translate":\"Press shift while holding to eat\",\"italic\":\"false\",\"color\":\"dark_green\"}"]}}
execute if block ~ ~ ~ minecraft:furnace{Items:[{Slot:0b,tag:{kitcraft:{id:"potato_sticks"}}}]} if entity @s[scores={kc_cooktime=198}] if block ~ ~ ~ minecraft:furnace{Items:[{Slot:2b,tag:{kitcraft:{id:"fries"}}}]} run replaceitem block ~ ~ ~ container.2 minecraft:dead_bubble_coral{kitcraft:{Eatable:1,sat:6,particle:"yellow",id:"fries",NoPlacing:1},CustomModelData:7050003,display:{Name:"{\"translate\":\"Fries\",\"italic\":\"false\"}",Lore:["{\"translate":\"Press shift while holding to eat\",\"italic\":\"false\",\"color\":\"dark_green\"}"]}}
execute if block ~ ~ ~ minecraft:furnace{Items:[{Slot:0b,tag:{kitcraft:{id:"potato_sticks"}}}]} if entity @s[scores={kc_cooktime=198}] unless block ~ ~ ~ minecraft:furnace{Items:[{Slot:2b}]} run function kitcraft:blocks/oven/cooking/count
execute if block ~ ~ ~ minecraft:furnace{Items:[{Slot:0b,tag:{kitcraft:{id:"potato_sticks"}}}]} if entity @s[scores={kc_cooktime=198}] if block ~ ~ ~ minecraft:furnace{Items:[{Slot:2b,tag:{kitcraft:{id:"fries"}}}]} run function kitcraft:blocks/oven/cooking/count

