#######
# Compiled from data/kitcraft/functions/random.mcscript
# to .//data/kitcraft/functions/random/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @e[scores={kc_random_range=1..}] at @s run function kitcraft:random/calculate
execute if score #x kc_random matches 2147483647.. run scoreboard players set #x kc_random 1

