#######
# Compiled from kitcraft/functions/blocks/cutting_board.mcscript
# to .//data/kitcraft/functions/blocks/cutting_board/place/place.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute align xyz positioned ~0.5 ~0 ~0.5 run summon armor_stand ~ ~-1.37508 ~ {Fire:1000,Tags:["kitcraft_cutting_board_vis"],DisabledSlots:4096,Invisible:1,Marker:1,NoGravity:1,ArmorItems:[{},{},{},{Count:1,id:armor_stand,tag:{CustomModelData:705102}}]}
tag @s remove kitcraft_cutting_board_init
