#######
# Compiled from kitcraft/functions/blocks/oven.mcscript
# to .//data/kitcraft/functions/blocks/oven/craft.mcfunction
#
# Generated by Minecraft Script for 1.13
######
advancement revoke @s only kitcraft:craft_oven_utility
recipe take @s kitcraft:oven
clear @s minecraft:structure_void 1
function kitcraft:give/blocks/oven
