#######
# Compiled from kitcraft/functions/blocks/oven.mcscript
# to .//data/kitcraft/functions/blocks/oven/detect_burntime.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @e[type=armor_stand,tag=kitcraft_oven] at @s store result score @s kc_burntime run data get block ~ ~ ~ BurnTime
execute as @e[type=armor_stand,tag=kitcraft_oven] at @s store result score @s kc_cooktime run data get block ~ ~ ~ CookTime
