#######
# Compiled from kitcraft/functions/blocks/oven.mcscript
# to .//data/kitcraft/functions/blocks/oven/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function kitcraft:blocks/oven/place/detect
function kitcraft:blocks/oven/destroy
