#######
# Compiled from kitcraft/functions/blocks/oven.mcscript
# to .//data/kitcraft/functions/blocks/oven/recipes.mcfunction
#
# Generated by Minecraft Script for 1.13
######

# Extended from kitcraft/functions/blocks/oven.mcscript
# to .//data/kitcraft/functions/blocks/oven/recipes.mcfunction
execute as @e[tag=kitcraft_oven] at @s if block ~ ~ ~ minecraft:furnace{Items:[{Slot:0b,tag:{kitcraft:{id:"potato_sticks"}}}]} unless block ~ ~ ~ minecraft:furnace{Items:[{Slot:0b,tag:{kitcraft:{Cookable:1}}}]} run data modify block ~ ~ ~ Items[{Slot:0b}].tag.kitcraft.Cookable set value 1
