#######
# Compiled from kitcraft/functions/blocks/oven.mcscript
# to .//data/kitcraft/functions/blocks/oven/recipes.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function kitcraft:blocks/oven/recipes/fries
