#######
# Compiled from kitcraft/functions/blocks/oven.mcscript
# to .//data/kitcraft/functions/blocks/oven/visuals.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @e[type=armor_stand,tag=kitcraft_oven,scores={kc_burntime=1..}] at @s if entity @s[y_rotation=135..-135] run particle flame ~ ~.2 ~-.5 0.1 0.01 0 0 1 normal
execute as @e[type=armor_stand,tag=kitcraft_oven,scores={kc_burntime=1..}] at @s if entity @s[y_rotation=-34.99..35] run particle flame ~ ~.2 ~.5 0.1 0.01 0 0 1 normal
