#######
# Compiled from kitcraft/functions/blocks/trash_can.mcscript
# to .//data/kitcraft/functions/blocks/trash_can/place/place_north.mcfunction
#
# Generated by Minecraft Script for 1.13
######
setblock ~ ~ ~ minecraft:hopper{TransferCooldown:1000000,CustomName:"{\"text\":\"Trash Can\",\"italic\":\"false\"}"}
tag @s remove kitcraft_trash_can_init
