#######
# Compiled from data/kitcraft/functions/eating.mcscript
# to .//data/kitcraft/functions/eating/food/ender_cookie/functionality.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute unless entity @s[nbt={SelectedItem:{tag:{kitcraft:{enderCookieData:{Written:1}}}}}] run summon minecraft:item ^ ^ ^.1 {Tags:["kitcraft_ender_cookie_write"],Item:{Count:1b,id:"minecraft:dead_bubble_coral",tag:{CustomModelData:7050008,display:{Name:"{\"translate\":\"Ender Cookie (written)\",\"italic\":false}"},kitcraft:{id:"ender_cookie",Eatable:1,sat:3,particle:"ender",NoPlacing:1,EatNoHunger:1,enderCookieData:{x:0f,y:0f,z:0f,Written:0}}}}}
execute unless entity @s[nbt={SelectedItem:{tag:{kitcraft:{enderCookieData:{Written:1}}}}}] as @e[type=item,limit=1,sort=nearest,tag=kitcraft_ender_cookie_write] run data modify entity @s Item.tag.kitcraft.enderCookieData.x set from entity @s Pos[0]
execute unless entity @s[nbt={SelectedItem:{tag:{kitcraft:{enderCookieData:{Written:1}}}}}] as @e[type=item,limit=1,sort=nearest,tag=kitcraft_ender_cookie_write] run data modify entity @s Item.tag.kitcraft.enderCookieData.y set from entity @s Pos[1]
execute unless entity @s[nbt={SelectedItem:{tag:{kitcraft:{enderCookieData:{Written:1}}}}}] as @e[type=item,limit=1,sort=nearest,tag=kitcraft_ender_cookie_write] run data modify entity @s Item.tag.kitcraft.enderCookieData.z set from entity @s Pos[2]
execute unless entity @s[nbt={SelectedItem:{tag:{kitcraft:{enderCookieData:{Written:1}}}}}] as @e[type=item,limit=1,sort=nearest,tag=kitcraft_ender_cookie_write] run data modify entity @s Item.tag.kitcraft.enderCookieData.Written set value 1
