#######
# Compiled from data/kitcraft/functions/eating.mcscript
# to .//data/kitcraft/functions/eating/food/ender_cookie/read_functionality_.mcfunction
#
# Generated by Minecraft Script for 1.13
######
data modify entity @e[type=minecraft:armor_stand,tag=kitcraft_ender_cookie_read,limit=1,sort=nearest] Pos[0] set from entity @s SelectedItem.tag.kitcraft.enderCookieData.x
data modify entity @e[type=minecraft:armor_stand,tag=kitcraft_ender_cookie_read,limit=1,sort=nearest] Pos[1] set from entity @s SelectedItem.tag.kitcraft.enderCookieData.y
data modify entity @e[type=minecraft:armor_stand,tag=kitcraft_ender_cookie_read,limit=1,sort=nearest] Pos[2] set from entity @s SelectedItem.tag.kitcraft.enderCookieData.z
data modify entity @e[type=minecraft:armor_stand,tag=kitcraft_ender_cookie_read,limit=1,sort=nearest] Rotation[0] set from entity @s SelectedItem.tag.kitcraft.enderCookieData.rx
data modify entity @e[type=minecraft:armor_stand,tag=kitcraft_ender_cookie_read,limit=1,sort=nearest] Rotation[1] set from entity @s SelectedItem.tag.kitcraft.enderCookieData.ry
execute at @e[type=minecraft:armor_stand,tag=kitcraft_ender_cookie_read,limit=1,sort=nearest] run tp @e[type=minecraft:armor_stand,tag=kitcraft_ender_cookie_read,limit=1,sort=nearest] ~ ~.25 ~
execute at @e[type=minecraft:armor_stand,limit=1,sort=nearest,tag=kitcraft_ender_cookie_read] run tp @s ~ ~ ~
kill @e[type=minecraft:armor_stand,tag=kitcraft_ender_cookie_read]