#######
# Compiled from kitcraft/functions/blocks/crop_harvester.mcscript
# to .//data/kitcraft/functions/blocks/crop_harvester/craft.mcfunction
#
# Generated by Minecraft Script for 1.13
######
advancement revoke @s only kitcraft:craft_crop_harvester_utility
recipe take @s kitcraft:crop_harvester
clear @s minecraft:structure_void 1
scoreboard players set @s kc_c_menu_m 17
