#######
# Compiled from kitcraft/functions/blocks/crop_harvester.mcscript
# to .//data/kitcraft/functions/blocks/crop_harvester/destroy.mcfunction
#
# Generated by Minecraft Script for 1.13
######
kill @s[type=armor_stand]
kill @e[type=armor_stand,tag=kitcraft_crop_harvester_vis,limit=1,sort=nearest]
data merge entity @e[type=item,limit=1,sort=nearest,distance=..2,nbt={Item:{id:"minecraft:cobblestone",Count:1b}}] {Item:{id:"minecraft:armor_stand",Count:1b,tag:{CustomModelData:705106,kitcraft:{id:"crop_harvester_place"},display:{Name:"{\"translate\":\"Crop Harvester\",\"italic\":\"false\"}",Lore:["{\"translate\":\"Right-click to place\",\"italic\":\"false\",\"color\":\"dark_green\"}"]},EntityTag:{NoGravity:1b,Invulnerable:1b,Small:1b,Marker:1b,Invisible:1b,PersistenceRequired:1b,Tags:["kitcraft_crop_harvester","kitcraft_crop_harvester_init"]}}}}
