#######
# Compiled from kitcraft/functions/blocks/crop_harvester.mcscript
# to .//data/kitcraft/functions/blocks/crop_harvester/harvest_custom.mcfunction
#
# Generated by Minecraft Script for 1.13
######
summon item ~ ~ ~ {Item:{id:"minecraft:arrow",Count:1b},Tags:["kitcraft_crop_harvester_harvested"]}
data modify entity @e[type=minecraft:item,tag=kitcraft_crop_harvester_harvested,limit=1,sort=nearest] Item.id set from entity @s HandItems[0].tag.kitcraft.cropDrop.crop.id
data modify entity @e[type=minecraft:item,tag=kitcraft_crop_harvester_harvested,limit=1,sort=nearest] Item.Count set from entity @s HandItems[0].tag.kitcraft.cropDrop.crop.Count
data modify entity @e[type=minecraft:item,tag=kitcraft_crop_harvester_harvested,limit=1,sort=nearest] Item.tag set from entity @s HandItems[0].tag.kitcraft.cropDrop.crop.tag
tag @e[type=minecraft:item,tag=kitcraft_crop_harvester_harvested,limit=1,sort=nearest] remove kitcraft_crop_harvester_harvested
summon item ~ ~ ~ {Item:{id:"minecraft:arrow",Count:1b},Tags:["kitcraft_crop_harvester_harvested"]}
data modify entity @e[type=minecraft:item,tag=kitcraft_crop_harvester_harvested,limit=1,sort=nearest] Item.id set from entity @s HandItems[0].tag.kitcraft.cropDrop.seed.id
data modify entity @e[type=minecraft:item,tag=kitcraft_crop_harvester_harvested,limit=1,sort=nearest] Item.Count set from entity @s HandItems[0].tag.kitcraft.cropDrop.seed.Count
data modify entity @e[type=minecraft:item,tag=kitcraft_crop_harvester_harvested,limit=1,sort=nearest] Item.tag set from entity @s HandItems[0].tag.kitcraft.cropDrop.seed.tag
tag @e[type=minecraft:item,tag=kitcraft_crop_harvester_harvested,limit=1,sort=nearest] remove kitcraft_crop_harvester_harvested
summon item ~ ~ ~ {Item:{id:"minecraft:dead_bubble_coral",Count:1b,tag:{CustomModelData:7051001,kitcraft:{replantCrop:"",NoPickup:1}}},Tags:["kitcraft_crop_harvester_replant"]}
data modify entity @e[type=minecraft:item,tag=kitcraft_crop_harvester_replant,limit=1,sort=nearest] Item.tag.kitcraft.replantCrop set from entity @s HandItems[0].tag.kitcraft.cropDrop.replant
function #kitcraft:crop_harvester_replant
kill @e[type=item,tag=kitcraft_crop_harvester_replant]
execute positioned ~ ~-1.5 ~ run kill @e[type=armor_stand,tag=kitcraft_lettuce_vis,distance=...5,limit=1,sort=nearest]
kill @s
