#######
# Compiled from kitcraft/functions/blocks/crop_harvester.mcscript
# to .//data/kitcraft/functions/blocks/crop_harvester/harvest.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if block ~ ~ ~ minecraft:farmland align xz run summon armor_stand ~.5 ~ ~.5 {NoGravity:1b,Marker:1b,Small:1b,Invisible:1b,Tags:["kitcraft_crop_harvester_detect"]}
execute if block ~ ~ ~ minecraft:farmland if block ~ ~1 ~ minecraft:wheat[age=7] run setblock ~ ~1 ~ minecraft:wheat[age=0] destroy
execute if block ~ ~ ~ minecraft:farmland if block ~ ~1 ~ minecraft:potatoes[age=7] run setblock ~ ~1 ~ minecraft:potatoes[age=0] destroy
execute if block ~ ~ ~ minecraft:farmland if block ~ ~1 ~ minecraft:beetroots[age=3] run setblock ~ ~1 ~ minecraft:beetroots[age=0] destroy
execute if block ~ ~ ~ minecraft:farmland if block ~ ~1 ~ minecraft:carrots[age=7] run setblock ~ ~1 ~ minecraft:carrots[age=0] destroy

execute if block ~ ~ ~ minecraft:dirt align xz run summon armor_stand ~.5 ~ ~.5 {NoGravity:1b,Marker:1b,Small:1b,Invisible:1b,Tags:["kitcraft_crop_harvester_detect"]}
execute if block ~ ~ ~ minecraft:dirt if block ~ ~1 ~ minecraft:pumpkin run setblock ~ ~1 ~ air destroy
execute if block ~ ~ ~ minecraft:dirt if block ~ ~1 ~ minecraft:melon run setblock ~ ~1 ~ air destroy
execute if block ~ ~ ~ minecraft:dirt if block ~ ~1 ~ minecraft:sugar_cane if block ~ ~2 ~ minecraft:sugar_cane run setblock ~ ~2 ~ air destroy
execute if block ~ ~ ~ minecraft:dirt if block ~ ~1 ~ minecraft:bamboo if block ~ ~2 ~ minecraft:bamboo run setblock ~ ~2 ~ air destroy
execute if block ~ ~ ~ minecraft:dirt if block ~ ~1 ~ minecraft:kelp_plant if block ~ ~2 ~ minecraft:kelp run setblock ~ ~2 ~ water destroy

execute positioned ~1 ~ ~ if block ~ ~ ~ minecraft:farmland unless entity @e[type=armor_stand,distance=...75,tag=kitcraft_crop_harvester_detect] run scoreboard players add @s kc_count 1
execute positioned ~-1 ~ ~ if block ~ ~ ~ minecraft:farmland unless entity @e[type=armor_stand,distance=...75,tag=kitcraft_crop_harvester_detect] run scoreboard players add @s kc_count 1
execute positioned ~ ~ ~1 if block ~ ~ ~ minecraft:farmland unless entity @e[type=armor_stand,distance=...75,tag=kitcraft_crop_harvester_detect] run scoreboard players add @s kc_count 1
execute positioned ~ ~ ~-1 if block ~ ~ ~ minecraft:farmland unless entity @e[type=armor_stand,distance=...75,tag=kitcraft_crop_harvester_detect] run scoreboard players add @s kc_count 1
execute positioned ~1 ~ ~ if block ~ ~ ~ minecraft:dirt unless entity @e[type=armor_stand,distance=...75,tag=kitcraft_crop_harvester_detect] run scoreboard players add @s kc_count 1
execute positioned ~-1 ~ ~ if block ~ ~ ~ minecraft:dirt unless entity @e[type=armor_stand,distance=...75,tag=kitcraft_crop_harvester_detect] run scoreboard players add @s kc_count 1
execute positioned ~ ~ ~1 if block ~ ~ ~ minecraft:dirt unless entity @e[type=armor_stand,distance=...75,tag=kitcraft_crop_harvester_detect] run scoreboard players add @s kc_count 1
execute positioned ~ ~ ~-1 if block ~ ~ ~ minecraft:dirt unless entity @e[type=armor_stand,distance=...75,tag=kitcraft_crop_harvester_detect] run scoreboard players add @s kc_count 1
execute positioned ~1 ~ ~ if block ~ ~ ~ minecraft:farmland unless entity @e[type=armor_stand,distance=...75,tag=kitcraft_crop_harvester_detect] if score @s kc_count matches ..121 run function kitcraft:blocks/crop_harvester/harvest
execute positioned ~-1 ~ ~ if block ~ ~ ~ minecraft:farmland unless entity @e[type=armor_stand,distance=...75,tag=kitcraft_crop_harvester_detect] if score @s kc_count matches ..121 run function kitcraft:blocks/crop_harvester/harvest
execute positioned ~ ~ ~1 if block ~ ~ ~ minecraft:farmland unless entity @e[type=armor_stand,distance=...75,tag=kitcraft_crop_harvester_detect] if score @s kc_count matches ..121 run function kitcraft:blocks/crop_harvester/harvest
execute positioned ~ ~ ~-1 if block ~ ~ ~ minecraft:farmland unless entity @e[type=armor_stand,distance=...75,tag=kitcraft_crop_harvester_detect] if score @s kc_count matches ..121 run function kitcraft:blocks/crop_harvester/harvest
execute positioned ~1 ~ ~ if block ~ ~ ~ minecraft:dirt unless entity @e[type=armor_stand,distance=...75,tag=kitcraft_crop_harvester_detect] if score @s kc_count matches ..121 run function kitcraft:blocks/crop_harvester/harvest
execute positioned ~-1 ~ ~ if block ~ ~ ~ minecraft:dirt unless entity @e[type=armor_stand,distance=...75,tag=kitcraft_crop_harvester_detect] if score @s kc_count matches ..121 run function kitcraft:blocks/crop_harvester/harvest
execute positioned ~ ~ ~1 if block ~ ~ ~ minecraft:dirt unless entity @e[type=armor_stand,distance=...75,tag=kitcraft_crop_harvester_detect] if score @s kc_count matches ..121 run function kitcraft:blocks/crop_harvester/harvest
execute positioned ~ ~ ~-1 if block ~ ~ ~ minecraft:dirt unless entity @e[type=armor_stand,distance=...75,tag=kitcraft_crop_harvester_detect] if score @s kc_count matches ..121 run function kitcraft:blocks/crop_harvester/harvest
execute positioned ~1 ~ ~ if block ~ ~ ~ minecraft:farmland unless entity @e[type=armor_stand,distance=...75,tag=kitcraft_crop_harvester_detect] run scoreboard players add @s kc_count 1
execute positioned ~-1 ~ ~ if block ~ ~ ~ minecraft:farmland unless entity @e[type=armor_stand,distance=...75,tag=kitcraft_crop_harvester_detect] run scoreboard players add @s kc_count 1
execute positioned ~ ~ ~1 if block ~ ~ ~ minecraft:farmland unless entity @e[type=armor_stand,distance=...75,tag=kitcraft_crop_harvester_detect] run scoreboard players add @s kc_count 1
execute positioned ~ ~ ~-1 if block ~ ~ ~ minecraft:farmland unless entity @e[type=armor_stand,distance=...75,tag=kitcraft_crop_harvester_detect] run scoreboard players add @s kc_count 1
execute positioned ~1 ~ ~ if block ~ ~ ~ minecraft:dirt unless entity @e[type=armor_stand,distance=...75,tag=kitcraft_crop_harvester_detect] run scoreboard players add @s kc_count 1
execute positioned ~-1 ~ ~ if block ~ ~ ~ minecraft:dirt unless entity @e[type=armor_stand,distance=...75,tag=kitcraft_crop_harvester_detect] run scoreboard players add @s kc_count 1
execute positioned ~ ~ ~1 if block ~ ~ ~ minecraft:dirt unless entity @e[type=armor_stand,distance=...75,tag=kitcraft_crop_harvester_detect] run scoreboard players add @s kc_count 1
execute positioned ~ ~ ~-1 if block ~ ~ ~ minecraft:dirt unless entity @e[type=armor_stand,distance=...75,tag=kitcraft_crop_harvester_detect] run scoreboard players add @s kc_count 1
execute positioned ~1 ~ ~ if block ~ ~ ~ minecraft:farmland unless entity @e[type=armor_stand,distance=...75,tag=kitcraft_crop_harvester_detect] if score @s kc_count matches ..121 run function kitcraft:blocks/crop_harvester/harvest
execute positioned ~-1 ~ ~ if block ~ ~ ~ minecraft:farmland unless entity @e[type=armor_stand,distance=...75,tag=kitcraft_crop_harvester_detect] if score @s kc_count matches ..121 run function kitcraft:blocks/crop_harvester/harvest
execute positioned ~ ~ ~1 if block ~ ~ ~ minecraft:farmland unless entity @e[type=armor_stand,distance=...75,tag=kitcraft_crop_harvester_detect] if score @s kc_count matches ..121 run function kitcraft:blocks/crop_harvester/harvest
execute positioned ~ ~ ~-1 if block ~ ~ ~ minecraft:farmland unless entity @e[type=armor_stand,distance=...75,tag=kitcraft_crop_harvester_detect] if score @s kc_count matches ..121 run function kitcraft:blocks/crop_harvester/harvest
execute positioned ~1 ~ ~ if block ~ ~ ~ minecraft:dirt unless entity @e[type=armor_stand,distance=...75,tag=kitcraft_crop_harvester_detect] if score @s kc_count matches ..121 run function kitcraft:blocks/crop_harvester/harvest
execute positioned ~-1 ~ ~ if block ~ ~ ~ minecraft:dirt unless entity @e[type=armor_stand,distance=...75,tag=kitcraft_crop_harvester_detect] if score @s kc_count matches ..121 run function kitcraft:blocks/crop_harvester/harvest
execute positioned ~ ~ ~1 if block ~ ~ ~ minecraft:dirt unless entity @e[type=armor_stand,distance=...75,tag=kitcraft_crop_harvester_detect] if score @s kc_count matches ..121 run function kitcraft:blocks/crop_harvester/harvest
execute positioned ~ ~ ~-1 if block ~ ~ ~ minecraft:dirt unless entity @e[type=armor_stand,distance=...75,tag=kitcraft_crop_harvester_detect] if score @s kc_count matches ..121 run function kitcraft:blocks/crop_harvester/harvest