#######
# Compiled from kitcraft/functions/blocks/crop_harvester.mcscript
# to .//data/kitcraft/functions/blocks/crop_harvester/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function kitcraft:blocks/crop_harvester/place/detect
execute as @e[tag=kitcraft_crop_harvester] at @s unless block ~ ~ ~ minecraft:cobblestone run function kitcraft:blocks/crop_harvester/destroy
execute as @e[tag=kitcraft_crop_harvester] at @s run scoreboard players reset @s kc_count
execute as @e[type=armor_stand,tag=kitcraft_crop_harvester_vis] run data merge entity @s {Fire:1000s}
kill @e[type=armor_stand,tag=kitcraft_crop_harvester_detect]
