#######
# Compiled from kitcraft/functions/blocks/crop_harvester.mcscript
# to .//data/kitcraft/functions/blocks/crop_harvester/replant.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @e[type=item,nbt={Item:{tag:{kitcraft:{replantCrop:"lettuce"}}}}] at @s run function kitcraft:crops/lettuce/place