#######
# Compiled from kitcraft/functions/blocks/sink.mcscript
# to .//data/kitcraft/functions/blocks/sink/empty_item/bucket.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{tag:{kitcraft:{containerItem:"bucket"}}}}] at @s run function kitcraft:blocks/sink/empty_item/visuals
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{tag:{kitcraft:{containerItem:"bucket"}}}}] at @s run data remove entity @s Item.tag
execute as @e[type=armor_stand,tag=kitcraft_sink] at @s as @e[type=item,distance=...5,nbt={Item:{tag:{kitcraft:{containerItem:"bucket"}}}}] at @s run data merge entity @s {Item:{id:"minecraft:bucket"}}
