#######
# Compiled from kitcraft/functions/blocks/sink.mcscript
# to .//data/kitcraft/functions/blocks/sink/empty_item/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function kitcraft:blocks/sink/empty_item/water_bucket
function kitcraft:blocks/sink/empty_item/milk_bucket
function kitcraft:blocks/sink/empty_item/lava_bucket
function kitcraft:blocks/sink/empty_item/potion
function kitcraft:blocks/sink/empty_item/pufferfish_bucket
function kitcraft:blocks/sink/empty_item/salmon_bucket
function kitcraft:blocks/sink/empty_item/cod_bucket
function kitcraft:blocks/sink/empty_item/tropical_fish_bucket
