#######
# Compiled from kitcraft/functions/blocks/sink.mcscript
# to .//data/kitcraft/functions/blocks/sink/empty_item/visuals.mcfunction
#
# Generated by Minecraft Script for 1.13
######
particle splash ~ ~1 ~ 0.25 0.1 0.25 1 10 normal
