#######
# Compiled from data/kitcraft/functions/food.mcscript
# to .//data/kitcraft/functions/food/ender_cookie_read.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function kitcraft:eating/advanced_food_consume
function kitcraft:eating/food/ender_cookie/read_functionality
scoreboard players reset @s kc_eattime
