#######
# Compiled from data/kitcraft/functions/food.mcscript
# to .//data/kitcraft/functions/food/lemon_soda.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function kitcraft:eating/advanced_food_consume
effect give @s minecraft:speed 60
give @s minecraft:glass_bottle
scoreboard players reset @s kc_eattime