#######
# Compiled from data/kitcraft/functions/food.mcscript
# to .//data/kitcraft/functions/food/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
#Tasty TNT
execute as @a[nbt={SelectedItem:{tag:{kitcraft:{id:"tasty_tnt"}}}}] at @s if score @s kc_eattime = @s kc_req_eattime run function kitcraft:food/tasty_tnt
#Ender Cookie
execute as @a[nbt={SelectedItem:{tag:{kitcraft:{id:"ender_cookie"}}}}] at @s if score @s kc_eattime = @s kc_req_eattime run function kitcraft:food/ender_cookie_write
execute as @a[nbt={SelectedItem:{tag:{kitcraft:{id:"ender_cookie_written"}}}}] at @s if score @s kc_eattime = @s kc_req_eattime run function kitcraft:food/ender_cookie_read
#Lemon Soda
execute as @a[nbt={SelectedItem:{tag:{kitcraft:{id:"lemon_soda"}}}}] at @s if score @s kc_eattime = @s kc_req_eattime run function kitcraft:food/lemon_soda
