#######
# Compiled from data/kitcraft/functions/food.mcscript
# to .//data/kitcraft/functions/food/tasty_tnt.mcfunction
#
# Generated by Minecraft Script for 1.13
######
summon creeper ~ ~.5 ~ {NoGravity:1b,Silent:1b,Fuse:1,ExplosionRadius:1b,ignited:1b}
clear @s minecraft:tnt{kitcraft:{id:"tasty_tnt"}} 1
scoreboard players reset @s kc_eattime
