#######
# Compiled from kitcraft/functions/blocks/kitchen_tile.mcscript
# to .//data/kitcraft/functions/blocks/kitchen_tile/destroy.mcfunction
#
# Generated by Minecraft Script for 1.13
######
data merge entity @e[type=item,distance=..0.8,limit=1,sort=nearest,nbt={Item:{id:"minecraft:quartz_block"}}] {Item:{id:"minecraft:firework_rocket",Count:1,tag:{CustomModelData:7050001,kitcraftBlock:1,Fireworks:{}}}}
kill @s
