#######
# Compiled from kitcraft/functions/blocks/kitchen_tile.mcscript
# to .//data/kitcraft/functions/blocks/kitchen_tile/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @e[type=firework_rocket,nbt={FireworksItem:{tag:{kitcraftBlock:1}}}] at @s unless block ~ ~ ~ air if block ~0.4 ~ ~ air run tp @s ~0.5 ~ ~
execute as @e[type=firework_rocket,nbt={FireworksItem:{tag:{kitcraftBlock:1}}}] at @s unless block ~ ~ ~ air if block ~-0.4 ~ ~ air run tp @s ~-0.5 ~ ~
execute as @e[type=firework_rocket,nbt={FireworksItem:{tag:{kitcraftBlock:1}}}] at @s unless block ~ ~ ~ air if block ~ ~ ~-0.4 air run tp @s ~ ~ ~-0.5
execute as @e[type=firework_rocket,nbt={FireworksItem:{tag:{kitcraftBlock:1}}}] at @s unless block ~ ~ ~ air if block ~ ~ ~0.4 air run tp @s ~ ~ ~0.5
execute as @e[type=firework_rocket,nbt={FireworksItem:{tag:{kitcraftBlock:1}}}] at @s unless block ~ ~ ~ air if block ~ ~-0.4 ~ air run tp @s ~ ~-0.5 ~
execute as @e[type=firework_rocket,nbt={FireworksItem:{tag:{kitcraftBlock:1}}}] at @s unless block ~ ~ ~ air if block ~ ~0.4 ~ air run tp @s ~ ~0.5 ~
execute as @e[type=firework_rocket,nbt={FireworksItem:{tag:{kitcraftBlock:1}}}] at @s align xyz if block ~ ~ ~ air run function kitcraft:blocks/kitchen_tile/place/detect

execute as @e[tag=isCustomBlock,tag=kitcraft_kitchen_tile] at @s if block ~ ~ ~ air run function kitcraft:blocks/kitchen_tile/destroy
execute as @e[tag=isCustomBlock,tag=kitcraft_kitchen_tile] run data merge entity @s {Fire:23000s}
