#######
# Compiled from data/kitcraft/functions/eating.mcscript
# to .//data/kitcraft/functions/eating/food/ender_cookie.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @a[nbt={SelectedItem:{tag:{kitcraft:{id:"ender_cookie"}}}}] at @s if score @s kc_eattime = @s kc_req_eattime run function kitcraft:eating/food/ender_cookie/write_functionality
execute as @a[nbt={SelectedItem:{tag:{kitcraft:{id:"ender_cookie"}}}}] at @s if score @s kc_eattime = @s kc_req_eattime run function kitcraft:eating/advanced_food_consume
execute as @a[nbt={SelectedItem:{tag:{kitcraft:{id:"ender_cookie"}}}}] at @s if score @s kc_eattime = @s kc_req_eattime run scoreboard players reset @s kc_eattime
execute as @a[nbt={SelectedItem:{tag:{kitcraft:{id:"ender_cookie_written"}}}}] at @s if score @s kc_eattime = @s kc_req_eattime run function kitcraft:eating/food/ender_cookie/read_functionality
execute as @a[nbt={SelectedItem:{tag:{kitcraft:{id:"ender_cookie_written"}}}}] at @s if score @s kc_eattime = @s kc_req_eattime run function kitcraft:eating/advanced_food_consume
execute as @a[nbt={SelectedItem:{tag:{kitcraft:{id:"ender_cookie_written"}}}}] at @s if score @s kc_eattime = @s kc_req_eattime run scoreboard players reset @s kc_eattime
