#######
# Compiled from data/kitcraft/functions/eating.mcscript
# to .//data/kitcraft/functions/eating/food/fries.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @a[nbt={SelectedItem:{tag:{kitcraft:{id:"fries"}}}}] at @s if score @s kc_eattime = @s kc_req_eattime run clear @s minecraft:dead_bubble_coral{kitcraft:{id:"fries"}} 1
