#######
# Compiled from data/kitcraft/functions/eating.mcscript
# to .//data/kitcraft/functions/eating/food/fries.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @a[scores={kc_eattime=39},nbt={SelectedItem:{tag:{kitcraft:{id:"fries"}}}}] at @s run function kitcraft:eating/saturate
execute as @a[scores={kc_eattime=39},nbt={SelectedItem:{tag:{kitcraft:{id:"fries"}}}}] at @s run clear @s minecraft:fire_charge{kitcraft:{id:"fries"}} 1