#######
# Compiled from kitcraft/functions/blocks/crop_harvester.mcscript
# to .//data/kitcraft/functions/blocks/crop_harvester/place/place.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tag @s remove kitcraft_crop_harvester_init
setblock ~ ~ ~ cobblestone
execute align xyz run summon armor_stand ~0.5 ~0.5 ~0.5 {Tags: ["kitcraft_crop_harvester_vis"],Invisible:1,Marker:1,NoGravity:1,ArmorItems:[{},{},{},{id:"minecraft:armor_stand",Count:1b,tag:{CustomModelData:705106}}]}
