#######
# Compiled from kitcraft/functions/crops/lettuce.mcscript
# to .//data/kitcraft/functions/crops/lettuce/fertilize.mcfunction
#
# Generated by Minecraft Script for 1.13
######
kill @e[type=item,nbt={Item:{id:"minecraft:bone_meal"}},limit=1,sort=nearest]
scoreboard players add @s kc_growth_time 4000
execute if score @s kc_growth_time > @s kc_req_g_time run scoreboard players operation @s kc_growth_time = @s kc_req_g_time
