#######
# Compiled from kitcraft/functions/crops/lettuce.mcscript
# to .//data/kitcraft/functions/crops/lettuce/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @e[tag=kitcraft_lettuce_setgt] at @s run scoreboard players operation @s kc_req_g_time += @s kc_random
execute as @e[tag=kitcraft_lettuce_setgt] at @s run scoreboard players reset @s kc_random
execute as @e[tag=kitcraft_lettuce_setgt] at @s run tag @s remove kitcraft_lettuce_setgt
execute as @e[tag=kitcraft_lettuce_vis] run data merge entity @s {Fire:100}
execute as @e[tag=kitcraft_lettuce] at @s if entity @e[distance=...75,type=item,nbt={Item:{id:"minecraft:tnt"}}] run function kitcraft:crops/lettuce/destroy
execute as @e[tag=kitcraft_lettuce] at @s unless block ~ ~-1 ~ minecraft:farmland run function kitcraft:crops/lettuce/destroy
execute as @e[tag=kitcraft_lettuce] at @s if score @s kc_req_g_time <= @s kc_growth_time run function kitcraft:crops/lettuce/harvest
execute as @e[tag=kitcraft_lettuce] at @s if score @s kc_req_g_time = @s kc_growth_time run function kitcraft:crops/lettuce/update
execute as @e[tag=kitcraft_lettuce] at @s unless score @s kc_req_g_time <= @s kc_growth_time run scoreboard players add @s kc_growth_time 1
execute as @e[tag=kitcraft_lettuce] at @s unless score @s kc_req_g_time <= @s kc_growth_time if entity @e[distance=...75,type=item,nbt={Item:{id:"minecraft:bone_meal",Count:1b}}] run function kitcraft:crops/lettuce/fertilize
function kitcraft:crops/lettuce/plant_detect
