#######
# Compiled from kitcraft/functions/crops/lettuce.mcscript
# to .//data/kitcraft/functions/crops/lettuce/set_req_growth_time.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard players set @s kc_random_range 4000
scoreboard players set @s kc_req_g_time 10000
tag @s remove kitcraft_lettuce_init
tag @s add kitcraft_lettuce_setgt
