#######
# Compiled from kitcraft/functions/crops/lettuce.mcscript
# to .//data/kitcraft/functions/crops/lettuce/update.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tag @s add kitcraft_crop_grown
replaceitem entity @s weapon.mainhand minecraft:dead_bubble_coral{CustomModelData:7051000,kitcraft:{cropDrop:{replant:"lettuce",crop:{id:"minecraft:player_head",Count:1b,tag:{kitcraft:{NoPlacing:1,id:"lettuce"},display:{Name:"{\"translate\":\"Lettuce\",\"color\":\"white\",\"italic\":false}"},SkullOwner:{Id:"1aa5d3fd-bfbe-4356-a3ed-40ddf2c3fc3e",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvN2Q4MDNkMTdlNThiNzE1MDU0OGIxMWJiNjVhNjIwZjI0OGIwYjdlYTYzZGUwZTFkOGU1ZmZjY2ViNjkzOTgifX19"}]}}}},seed:{id:"minecraft:firework_rocket",Count:0b,tag:{kitcraft:{id:"lettuce_seeds"},display:{Name:"{\"translate\":\"Lettuce Seeds\",\"italic\":false}",Lore:["{\"translate\":\"Right-click to plant\",\"color\":\"dark_green\",\"italic\":false}"]},CustomModelData:7050001,Fireworks:{}}}}}}
execute positioned ~ ~-1.5 ~ as @e[tag=kitcraft_lettuce_vis,limit=1,sort=nearest,distance=...1] run data merge entity @s {ArmorItems:[{},{},{},{id:"minecraft:player_head",Count:1b,tag:{SkullOwner:{Id:"1aa5d3fd-bfbe-4356-a3ed-40ddf2c3fc3e",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvN2Q4MDNkMTdlNThiNzE1MDU0OGIxMWJiNjVhNjIwZjI0OGIwYjdlYTYzZGUwZTFkOGU1ZmZjY2ViNjkzOTgifX19"}]}}}}]}
scoreboard players add @s kc_growth_time 1
