#######
# Compiled from kitcraft/functions/crops/lemon_tree.mcscript
# to .//data/kitcraft/functions/crops/lemon_tree/fruit/grow_detect.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if score @s kc_growth_time = @s kc_req_g_time if entity @s[tag=!kitcraft_fruit_grown] run function kitcraft:crops/lemon_tree/fruit/grow

