#######
# Compiled from kitcraft/functions/crops/lemon_tree.mcscript
# to .//data/kitcraft/functions/crops/lemon_tree/fruit/grow.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tag @s add kitcraft_fruit_grown
replaceitem entity @s weapon.mainhand minecraft:dead_bubble_coral{display:{Name:"{\"translate\":\"Lemon\",\"italic\":false}"},CustomModelData:7051001,kitcraft:{id:"lemon",NoPlacing:1}} 1
execute as @e[type=armor_stand,tag=kitcraft_lemon_tree_fruit_vis,limit=1,sort=nearest] run replaceitem entity @s armor.head minecraft:dead_tube_coral{CustomModelData:7050001} 1
