#######
# Compiled from kitcraft/functions/crops/lemon_tree.mcscript
# to .//data/kitcraft/functions/crops/lemon_tree/fruit/harvest.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute unless entity @s[nbt={HandItems:[{id:"minecraft:dead_bubble_coral"},{}]}] if entity @s[tag=kitcraft_fruit_grown] run scoreboard players set @s kc_growth_time 0
execute unless entity @s[nbt={HandItems:[{id:"minecraft:dead_bubble_coral"},{}]}] if entity @s[tag=kitcraft_fruit_grown] run replaceitem entity @e[type=armor_stand,tag=kitcraft_lemon_tree_fruit_vis,limit=1,sort=nearest] armor.head air
execute unless entity @s[nbt={HandItems:[{id:"minecraft:dead_bubble_coral"},{}]}] if entity @s[tag=kitcraft_fruit_grown] run function kitcraft:crops/lemon_tree/fruit/set_growth_time
execute unless entity @s[nbt={HandItems:[{id:"minecraft:dead_bubble_coral"},{}]}] if entity @s[tag=kitcraft_fruit_grown] run tag @s remove kitcraft_fruit_grown

