#######
# Compiled from kitcraft/functions/crops/lemon_tree.mcscript
# to .//data/kitcraft/functions/crops/lemon_tree/fruit/update.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute unless score @s kc_growth_time matches 1.. run scoreboard players add @s kc_growth_time 1

execute if score @s kc_growth_time <= @s kc_req_g_time run scoreboard players add @s kc_growth_time 1

