#######
# Compiled from kitcraft/functions/blocks/fruit_picker.mcscript
# to .//data/kitcraft/functions/blocks/fruit_picker/schedule/a.mcfunction
#
# Generated by Minecraft Script for 1.13
######
schedule function kitcraft:blocks/fruit_picker/schedule/b 15s
execute as @e[tag=kitcraft_fruit_picker] at @s align xyz positioned ~.5 ~.5 ~.5 run function kitcraft:blocks/fruit_picker/harvest
